### ISSUE TITLE
Cannot start tranga-api docker - get error "ChromiumDownl | Can't download browser version 1154303"

### ISSUE THREAD

**Issue by ryanovas** [C9Glax/tranga#106]
### What is broken?

I tried installing this for the first time from the docker-compose file created and it simply won't boot. Only difference is that I'm running it thru gluetun, but I have many containers in gluetun that work without issue.

### Log-output

```C#
[01/25/2024 00:42:53.535]        Tranga | 

 _______                                   
|_     _|.----..---.-..-----..-----..---.-.
  |   |  |   _||  _  ||     ||  _  ||  _  |
  |___|  |__|  |___._||__|__||___  ||___._|
                             |_____|       


[01/25/2024 00:42:53.542]        Tranga | TrangaSettings:
        DownloadLocation: /Manga
        workingDirectory: /usr/share/tranga-api
        jobsFolderPath: /usr/share/tranga-api/jobs
        settingsFilePath: /usr/share/tranga-api/settings.json
                notificationConnectors: /usr/share/tranga-api/notificationConnectors.json
                libraryConnectors: /usr/share/tranga-api/libraryConnectors.json

[01/25/2024 00:42:53.555] ChromiumDownl | Downloading headless browser
[01/25/2024 00:42:53.897] ChromiumDownl | Can't download browser version 1154303
Unhandled exception. System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.)
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at Tranga.MangaConnectors.ChromiumDownloadClient.DownloadBrowser() in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 37
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Tranga.MangaConnectors.ChromiumDownloadClient..ctor(GlobalBase clone, Dictionary`2 rateLimitRequestsPerMinute) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 58
   at Tranga.MangaConnectors.Mangasee..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/Mangasee.cs:line 15
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 19
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 50
```

### Additional stuff

My docker compose:

```
version: "3.3"
services:
  gluetun:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - # various env vars that connect to my VPN
    volumes:
      - /home/ryan/docker-files/gluetun:/gluetun
    image: qmcgaw/gluetun
    ports:
      - 8100:8100/tcp # HTTP control server
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 30900:30900 # qBittorrent
      - 30681:30681 # qBittorrent
      - 30681:30681/udp # qBittorrent
      - 9696:9696 # Prowlar
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 8787:8787 # Readarr Books
      - 6767:6767 # Bazarr
      - 5656:5656 # Kapowarr
      - 6531:6531 # Tranga
    restart: unless-stopped
  tranga-api:
    image: glax/tranga-api:latest
    container_name: tranga-api
    network_mode: service:gluetun
    volumes:
      - /mnt/external-media/media/library/manga:/Manga
      - /home/ryan/docker-files/tranga:/usr/share/tranga-api
    restart: unless-stopped
  tranga-website:
    image: glax/tranga-website:latest
    container_name: tranga-website
    ports:
      - 9555:80
    depends_on:
      - tranga-api
    restart: unless-stopped
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /home/ryan/docker-files/komga:/config
      - /mnt/external-media/media/library/comics:/data
    ports:
      - 25600:25600
    user: 1000:1000
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
```

**Comment by C9Glax** [comment]
From what I can tell the tranga container is not able to connect to a) the internet or b) to the chromium archive.
Your exception is thrown [here](https://github.com/C9Glax/tranga/blob/b5be4e0dd88f4be65d0cf48804042642b51d0e7e/Tranga/MangaConnectors/ChromiumDownloadClient.cs#L36) with [this](https://www.puppeteersharp.com/api/PuppeteerSharp.BrowserFetcher.html#PuppeteerSharp_BrowserFetcher_CanDownloadAsync_System_String_) being the problem. e.g. tranga is not able to make that request.
The browser version is available 
![image](https://github.com/C9Glax/tranga/assets/13404778/1291bc3e-cbf1-4a03-97b3-e3d8691e75a1)
