### ISSUE TITLE
[It broke]: Tranga is Unable to Start

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#108]
### What is broken?

Tranga is unable to start the browser which causes the entire program to restart

### Log-output

```C#
[01/31/2024 03:19:16.692]        Tranga | TrangaSettings:

	DownloadLocation: /Manga

	workingDirectory: /usr/share/tranga-api

	jobsFolderPath: /usr/share/tranga-api/jobs

	settingsFilePath: /usr/share/tranga-api/settings.json

		notificationConnectors: /usr/share/tranga-api/notificationConnectors.json

		libraryConnectors: /usr/share/tranga-api/libraryConnectors.json

[01/31/2024 03:19:16.718] ChromiumDownl | Starting Browser.

Unhandled exception. System.AggregateException: One or more errors occurred. (Timed out after 10000 ms while trying to connect to Base!)

 ---> PuppeteerSharp.ProcessException: Timed out after 10000 ms while trying to connect to Base!

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 83

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 89

   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 62

   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 95

   at Tranga.MangaConnectors.ChromiumDownloadClient.DownloadBrowser() in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 43

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at Tranga.MangaConnectors.ChromiumDownloadClient..ctor(GlobalBase clone, Dictionary`2 rateLimitRequestsPerMinute) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 58

   at Tranga.MangaConnectors.Mangasee..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/Mangasee.cs:line 15

   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 19

   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 50
```

**Comment by C9Glax** [comment]
Hmmm, I am thinking if I should just disable connector that use the browser when it fails to start...

**Comment by db-2001** [comment]
Tried to pull the latest image after the custom user agent and rate limiting changes and got these errors: 

Unhandled exception. System.ArgumentException: Can not convert Null to DateTime.

   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)

   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)

   at Newtonsoft.Json.Linq.JToken.ToObject[T]()

   at Tranga.Jobs.JobJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/Jobs/JobJsonConverter.cs:line 28

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)

   at Tranga.Jobs.JobBoss.LoadJobsList(HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 161

   at Tranga.Jobs.JobBoss..ctor(GlobalBase clone, HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 15

   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 28

   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 50

**Comment by C9Glax** [comment]
I don't think it's related to that tbh. Can you try the fix I just pushed.

**Comment by db-2001** [comment]
Yeah, it's working again.
