### ISSUE TITLE
[It broke]: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ProfesseurIssou** [C9Glax/tranga#126]
### What is broken?

Hello, i have this error, i try the LATEST and the CuttingEdge version, but i have the same error

### Log-output

```C#
2024-02-12T19:40:16.620964429Z |_     _|.----..---.-..-----..-----..---.-.
2024-02-12T19:40:16.620966182Z   |   |  |   _||  _  ||     ||  _  ||  _  |
2024-02-12T19:40:16.620967895Z   |___|  |__|  |___._||__|__||___  ||___._|
2024-02-12T19:40:16.620969508Z                              |_____|       
2024-02-12T19:40:16.620971121Z 
2024-02-12T19:40:16.620972674Z 
2024-02-12T19:40:16.622164523Z [02/12/2024 19:40:16.622]        Tranga | TrangaSettings:
2024-02-12T19:40:16.622182917Z 	DownloadLocation: /Manga
2024-02-12T19:40:16.622186504Z 	workingDirectory: /usr/share/tranga-api
2024-02-12T19:40:16.622188858Z 	jobsFolderPath: /usr/share/tranga-api/jobs
2024-02-12T19:40:16.622190932Z 	settingsFilePath: /usr/share/tranga-api/settings.json
2024-02-12T19:40:16.622193006Z 		notificationConnectors: /usr/share/tranga-api/notificationConnectors.json
2024-02-12T19:40:16.622195200Z 		libraryConnectors: /usr/share/tranga-api/libraryConnectors.json
2024-02-12T19:40:16.622197274Z 
2024-02-12T19:40:16.640521241Z [02/12/2024 19:40:16.640] ChromiumDownl | Starting Browser.
2024-02-12T19:40:16.844338651Z [02/12/2024 19:40:16.844] ChromiumDownl | Starting Browser.
2024-02-12T19:40:17.047229483Z Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2024-02-12T19:40:17.047248458Z    at Tranga.Jobs.JobBoss.<>c__DisplayClass21_1.<LoadJobsList>b__2(Job jjob) in /src/Tranga/Jobs/JobBoss.cs:line 161
2024-02-12T19:40:17.047252376Z    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2024-02-12T19:40:17.047254991Z    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2024-02-12T19:40:17.047257305Z    at Tranga.Jobs.JobBoss.LoadJobsList(HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 161
2024-02-12T19:40:17.047259539Z    at Tranga.Jobs.JobBoss..ctor(GlobalBase clone, HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 15
2024-02-12T19:40:17.047278395Z    at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 29
2024-02-12T19:40:17.047286890Z    at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 50
```

**Comment by C9Glax** [comment]
I will be moving to a different Queue-System that should hopefully be less convoluted...
I think what was happening was that the ParentJob finished at some point, got deleted and left the child-jobs orphaned...
https://github.com/C9Glax/tranga/tree/JobQueue
