### ISSUE TITLE
Mangasee missing Reference

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#135]
https://github.com/C9Glax/tranga-website/issues/54#issuecomment-1968315489

Never mind, I felt abusive saying there’s an issue and making you wait hours so I went digging lol. I think I found it, basically on system start there’s a ton of Adding Job to Queue followed by
```[02/27/2024 22:11:12.223]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-cmFua2Vyc3JldHVybnJlbWFrZTIwMjE= Manga: Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.223]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-b3ZlcmdlYXJlZDIwMTc= Manga: Publication Overgeared b3ZlcmdlYXJlZDIwMTc=
[02/27/2024 22:11:12.224]     Manganato | Copy cover Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.224]     Manganato | Cover exists Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.224]     Manganato | Retrieving chapter-info Chapter Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE= 4  Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.630]     Manganato | Downloading Images for /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz
[02/27/2024 22:11:12.631]     Manganato | Downloading image 001/058
[02/27/2024 22:11:12.781]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 002/058 OK
[02/27/2024 22:11:12.781]     Manganato | Downloading image 002/058
[02/27/2024 22:11:12.781] HttpDownloadC | Waiting 0.9985997 seconds
[02/27/2024 22:11:13.806]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 003/058 OK
[02/27/2024 22:11:13.806]     Manganato | Downloading image 003/058
[02/27/2024 22:11:13.806] HttpDownloadC | Waiting 0.9991993 seconds
[02/27/2024 22:11:14.829]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 004/058 OK
[02/27/2024 22:11:14.829]     Manganato | Downloading image 004/058
[02/27/2024 22:11:14.829] HttpDownloadC | Waiting 0.9993405 seconds
[02/27/2024 22:11:15.239] ChromiumDownl | Page loaded.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Tranga.MangaConnectors.Mangasee.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 134
   at Tranga.MangaConnectors.Mangasee.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/Mangasee.cs:line 123
   at Tranga.MangaConnectors.Mangasee.GetMangaFromId(String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 113
   at Tranga.Jobs.UpdateMetadata.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/UpdateMetadata.cs:line 27
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 248
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74```

_Originally posted by @yacob841 in https://github.com/C9Glax/tranga-website/issues/54#issuecomment-1968315489_

**Comment by yacob841** [comment]
Not sure if the latest update was meant to fix this or not but I updated to the latest and it still crashes but the error seems to have changed 

```[02/28/2024 04:59:58.579] ChromiumDownl | Browser download progress: 97.16 %
[02/28/2024 04:59:59.154] ChromiumDownl | Browser downloaded.
[02/28/2024 05:00:19.185] ChromiumDownl | Starting Browser.
Unhandled exception. System.AggregateException: One or more errors occurred. (Timed out after 10000 ms while trying to connect to Base!)
 ---> PuppeteerSharp.ProcessException: Timed out after 10000 ms while trying to connect to Base!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 62
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 95
   at Tranga.MangaConnectors.ChromiumDownloadClient.DownloadBrowser() in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 43
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Tranga.MangaConnectors.ChromiumDownloadClient..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 58
   at Tranga.MangaConnectors.Mangasee..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/Mangasee.cs:line 15
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 19
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53```

**Comment by yacob841** [comment]
I was impatient so I just deleted all the jobs in the folder and was able to reboot again. I was thinking it might be useful to put the user readable manga name and chapter number in the job name that way if this thing happens in the future I would only have to delete the problem job and not have to either manually open each of them or wipe my library.

**Comment by C9Glax** [comment]
Yea, the Manganame is in the logs
`[02/27/2024 22:11:12.223]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-b3ZlcmdlYXJlZDIwMTc= Manga: Publication Overgeared b3ZlcmdlYXJlZDIwMTc=`
But I agree the filename should include that information

**Comment by C9Glax** [comment]
Also [this happens](https://github.com/C9Glax/tranga/issues/135#issuecomment-1968943368) sometimes when the headless browser isn't quick enough to start. I think I will increase the timeout for that to 30 seconds...

**Comment by db-2001** [comment]
I'm also having issues with Mangasee timing out and not downloading new chapters or invalid files being created that Kavita can't see
