### ISSUE TITLE
[It broke]: Crashes with "Sequence contains no matching element"

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#137]
### What is broken?

The container crashes on start after about 20 seconds due to an issue with Taming Master on Mangonato.

### Log-output

```C#
[03/04/2024 07:42:50.651]     Manganato | Getting new Chapters for Publication Taming Master dGFtaW5nbWFzdGVyMjAyMA==
[03/04/2024 07:42:50.653]     Manganato | Getting chapters Publication Taming Master dGFtaW5nbWFzdGVyMjAyMA==
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tranga.MangaConnectors.Manganato.ParseChaptersFromHtml(Manga manga, HtmlDocument document) in /src/Tranga/MangaConnectors/Manganato.cs:line 159
   at Tranga.MangaConnectors.Manganato.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Manganato.cs:line 150
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 61
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 248
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

### Additional stuff

This combined with the other error I got causing crashes leads to me to think it would be nice if you could try and catch errors to prevent system crashes and then you can display the errors somewhere.

**Comment by db-2001** [comment]
Does this happen consistently with this manga?

**Comment by C9Glax** [comment]
@yacob841 We need your input. Does this still happen?

**Comment by yacob841** [comment]
I deleted the manga and then re-added it (can’t remember if it was same source or not) and the issue stopped happening.
