### ISSUE TITLE
[It broke]: Connector issues

### ISSUE THREAD

**Issue by Nas-77** [C9Glax/tranga#146]
### What is broken?

Hi, I think my tranga instance suddenly couldn't connect to any of the connectors.  I am sure that the computer has access to the internet as I am able to access the tranga-website, I am hosting over cloudflare. 

Connectors I am using is Manganato, Mangadex, and Mangakatana.

### Log-output

```C#
2024-03-14 15:01:32    --- End of inner exception stack trace ---
2024-03-14 15:01:32    --- End of inner exception stack trace ---
2024-03-14 15:01:32    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
2024-03-14 15:01:32    at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-03-14 15:01:32    at Tranga.MangaConnectors.HttpDownloadClient.MakeRequestInternal(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/HttpDownloadClient.cs:line 74
2024-03-14 15:01:32 [03/14/2024 07:01:32.747] UpdateMetadat | Could not find Manga Publication Watashi Yori Tsuyoi Otoko to Kekkon Shitai no d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy
2024-03-14 15:01:42 [03/14/2024 07:01:42.758] HttpDownloadC | Request timed out https://chapmanganato.com/manga-jd986438.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
2024-03-14 15:01:42  ---> System.TimeoutException: A task was canceled.
2024-03-14 15:01:42  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
2024-03-14 15:01:42    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
2024-03-14 15:01:42    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
2024-03-14 15:01:42    at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-03-14 15:01:42    --- End of inner exception stack trace ---
2024-03-14 15:01:42    --- End of inner exception stack trace ---
2024-03-14 15:01:42    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
2024-03-14 15:01:42    at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-03-14 15:01:42    at Tranga.MangaConnectors.HttpDownloadClient.MakeRequestInternal(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/HttpDownloadClient.cs:line 74
2024-03-14 15:01:42 [03/14/2024 07:01:42.761] UpdateMetadat | Could not find Manga Publication Absolute Martial Arts YWJzb2x1dGVtYXJ0aWFsYXJ0czIwMjA=
2024-03-14 15:01:42 [03/14/2024 07:01:42.867]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-Y2hyb25pY2xlc29mYXJldHVybmVyMjAyNA== Manga: Publication Chronicles of a Returner Y2hyb25pY2xlc29mYXJldHVybmVyMjAyNA==
2024-03-14 15:01:42 [03/14/2024 07:01:42.879]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-bXl3aWZlaXN0aGV1bmlvbmxlYWRlcm9mbWFydGlhbGFydHNjaXJjbGVzMjAyMQ== Manga: Publication My Wife Is the Union Leader of Martial Arts Circles bXl3aWZlaXN0aGV1bmlvbmxlYWRlcm9mbWFydGlhbGFydHNjaXJjbGVzMjAyMQ==
2024-03-14 15:01:42 [03/14/2024 07:01:42.882]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-ZGFkYXNrZWRtZXRvY2hvb3Nlb25lb2Z0ZW5nb2RkZXNzZXN0b21hcnJ5MjAyMg== Manga: Publication Dad Asked Me To Choose One Of Ten Goddesses To Marry ZGFkYXNrZWRtZXRvY2hvb3Nlb25lb2Z0ZW5nb2RkZXNzZXN0b21hcnJ5MjAyMg==
2024-03-14 15:01:42 [03/14/2024 07:01:42.885]       JobBoss | Removing Tranga.Jobs.UpdateMetadata-dGhlZXhpbGVkcmVpbmNhcm5hdGVkaGVhdnlrbmlnaHRpc3Vucml2YWxlZGluZ2FtZWtub3dsZWRnZTIwMjQ= Manga: Publication The Exiled Reincarnated Heavy Knight Is Unrivaled in Game Knowledge dGhlZXhpbGVkcmVpbmNhcm5hdGVkaGVhdnlrbmlnaHRpc3Vucml2YWxlZGluZ2FtZWtub3dsZWRnZTIwMjQ=
2024-03-14 15:01:42 [03/14/2024 07:01:42.886] UpdateMetadat | Cancelling Tranga.Jobs.UpdateMetadata-dGhlZXhpbGVkcmVpbmNhcm5hdGVkaGVhdnlrbmlnaHRpc3Vucml2YWxlZGluZ2FtZWtub3dsZWRnZTIwMjQ= Manga: Publication The Exiled Reincarnated Heavy Knight Is Unrivaled in Game Knowledge dGhlZXhpbGVkcmVpbmNhcm5hdGVkaGVhdnlrbmlnaHRpc3Vucml2YWxlZGluZ2FtZWtub3dsZWRnZTIwMjQ=
2024-03-14 15:01:42 [03/14/2024 07:01:42.894]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-dGhlZXhpbGVkcmVpbmNhcm5hdGVkaGVhdnlrbmlnaHRpc3Vucml2YWxlZGluZ2FtZWtub3dsZWRnZTIwMjQ=.json
2024-03-14 15:01:42 [03/14/2024 07:01:42.907]       JobBoss | Next job in -00:07:03.9953074 Tranga.Jobs.DownloadNewChapters-YWZ0ZXJiZWluZ2NhbGxlZGFoZXJvdGhldW5yaXZhbGVkbWFuc3RhcnRzYWZhbWlseTIwMjQ=
2024-03-14 15:01:42 [03/14/2024 07:01:42.909]       JobBoss | Removing Tranga.Jobs.UpdateMetadata-d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy Manga: Publication Watashi Yori Tsuyoi Otoko to Kekkon Shitai no d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy
2024-03-14 15:01:42 [03/14/2024 07:01:42.911] UpdateMetadat | Cancelling Tranga.Jobs.UpdateMetadata-d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy Manga: Publication Watashi Yori Tsuyoi Otoko to Kekkon Shitai no d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy
2024-03-14 15:01:42 [03/14/2024 07:01:42.914]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-d2F0YXNoaXlvcml0c3V5b2lvdG9rb3Rva2Vra29uc2hpdGFpbm8yMDIy.json
2024-03-14 15:01:42 [03/14/2024 07:01:42.920]       JobBoss | Next job in -00:07:04.0087544 Tranga.Jobs.DownloadNewChapters-YWZ0ZXJiZWluZ2NhbGxlZGFoZXJvdGhldW5yaXZhbGVkbWFuc3RhcnRzYWZhbWlseTIwMjQ=
```

**Comment by Nas-77** [comment]
Restarted my computer and docker, seemed to have fixed the issue. Sorry for the inconvenience.
