### ISSUE TITLE
[It broke]: MangaLife cannot download manga

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#149]
### What is broken?

MangaLife is unable to download chapters for https://www.manga4life.com/manga/Sekai-de-Yuuitsu-no-Tenshokushi -- this is just an example manga I was using to try and debug why Mangasee isn't working

### Log-output

```C#
Unhandled exception. System.AggregateException: One or more errors occurred. (No node found for selector: [class*='ShowAllChapters'])

 ---> PuppeteerSharp.SelectorException: No node found for selector: [class*='ShowAllChapters']

   at PuppeteerSharp.IsolatedWorld.ClickAsync(String selector, ClickOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/IsolatedWorld.cs:line 336

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.Wait()

   at Tranga.MangaConnectors.ChromiumDownloadClient.MakeRequestInternal(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 85

   at Tranga.MangaConnectors.DownloadClient.MakeRequest(String url, RequestType requestType, String referrer, String clickButton) in /src/Tranga/MangaConnectors/DownloadClient.cs:line 34

   at Tranga.MangaConnectors.MangaLife.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaLife.cs:line 133

   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 83

   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36

   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 94

   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 232

   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Fix is in `cuttingedge`-branch. Was unable to click a "Load more Chapters" button if it didn't exist and crashed.
