### ISSUE TITLE
[It broke]: Crashes on start 'The file '/usr/share/tranga-api/logs' already exists.'

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#169]
### What is broken?

Crashes on start with /log already exists error. Attempted repulling and still crashes.

### Log-output

```C#
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 18
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
```

**Comment by C9Glax** [comment]
Delete the `logs` file in your settings folder (wherever `/usr/share/tranga-api`) is mounted.

**Comment by yacob841** [comment]
Yes, that fixes it but I was posting because I figure already seeing logs should be a reason for container crashing right?
