### ISSUE TITLE
Mangaworld broken

### ISSUE THREAD

**Issue by bubez81** [C9Glax/tranga#185]
### What is broken?

Hi today I can’t search on Mangaworld anymore. Think something changed on Mangaworld site?

### Log-output

And suddenly 

<img width="1480" alt="Screenshot 2024-05-27 alle 18 41 39" src="https://github.com/C9Glax/tranga/assets/19486458/894cf393-e89a-4ca0-b49d-b1a306d62ce2">

**Comment by bubez81** [comment]
With a fresh install no error on start, I can search for example on manganato but no response with mangaworld:

<img width="938" alt="Screenshot 2024-06-01 alle 16 56 07" src="https://github.com/C9Glax/tranga/assets/19486458/b37f8e9d-7954-428e-9a82-1bac01bc1d4d">

**Comment by C9Glax** [comment]
I have had varying success with Mangaworld, didn't have time yet to test locally...

**Comment by bubez81** [comment]
Tell me if you need help to test something

**Comment by bubez81** [comment]
Hi, any news on this issue? Can I help in any way?

**Comment by bubez81** [comment]
The real problem is that suddenly stop working maybe the url is changed again?

**Comment by C9Glax** [comment]
Sorry for getting back to you so late, think I fixed the issue.
If so please close

**Comment by bubez81** [comment]
Hello! Everything ok? I hope you are doing well.

About Mangaworld problem, now the error is changed

'     
[06/30/2024 10:23:59.626]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-23-59.log
[06/30/2024 10:24:01.475]        Tranga | 
 _______                                   
|_     _|.----..---.-..-----..-----..---.-.
  |   |  |   _||  _  ||     ||  _  ||  _  |
  |___|  |__|  |___._||__|__||___  ||___._|
                             |_____|       
[06/30/2024 10:24:01.475]        Tranga | TrangaSettings:
	DownloadLocation: /Manga
	workingDirectory: /usr/share/tranga-api
	jobsFolderPath: /usr/share/tranga-api/jobs
	settingsFilePath: /usr/share/tranga-api/settings.json
		notificationConnectors: /usr/share/tranga-api/notificationConnectors.json
		libraryConnectors: /usr/share/tranga-api/libraryConnectors.json
[06/30/2024 10:24:02.339] ChromiumDownl | Downloading headless browser
[06/30/2024 10:24:06.180] ChromiumDownl | Browser download progress: 0.01 %
[06/30/2024 10:24:06.180] ChromiumDownl | Browser download progress: 0.00 %
[06/30/2024 10:24:07.181] ChromiumDownl | Browser download progress: 5.84 %
[06/30/2024 10:24:08.181] ChromiumDownl | Browser download progress: 28.49 %
[06/30/2024 10:24:08.183] ChromiumDownl | Browser download progress: 28.48 %
[06/30/2024 10:24:09.198] ChromiumDownl | Browser download progress: 53.44 %
[06/30/2024 10:24:09.199] ChromiumDownl | Browser download progress: 53.43 %
[06/30/2024 10:24:10.208] ChromiumDownl | Browser download progress: 77.69 %
[06/30/2024 10:24:11.138] ChromiumDownl | Browser downloaded.
[06/30/2024 10:24:14.589] ChromiumDownl | Starting Browser. (30000ms timeout)
[06/30/2024 10:24:17.384] ChromiumDownl | Starting Browser. (30000ms timeout)
[06/30/2024 10:24:17.464]       JobBoss | Next job in  
[06/30/2024 10:24:17.558]        Server | Listening on http://*:6531/
[06/30/2024 10:24:51.359]    Mangaworld | Searching Publications. Term="Blue lock"
[06/30/2024 10:24:52.435]    Mangaworld | Saving cover to /usr/share/tranga-api/imageCache/cdn.mangaworld.ac-1848-blue-lock.jpg
[06/30/2024 10:24:52.443]    Mangaworld | Retrieved 1 publications. Term="Blue lock"
[06/30/2024 10:26:12.145]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-26-12.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:26:32.681]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-26-32.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:26:53.269]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-26-53.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:27:11.18 ]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-27-10.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:27:31.507]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-27-31.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:27:49.213]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-27-49.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:03.242]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-3.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:13.321]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-13.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:24.76 ]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-24.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:34.269]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-34.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:44.570]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-44.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61
[06/30/2024 10:28:55.867]        Logger | Logfile: /usr/share/tranga-api/logs/06/30/2024_10-28-55.log
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Tranga.TrangaSettings..ctor(String downloadLocation, String workingDirectory, Nullable`1 apiPortNumber) in /src/Tranga/TrangaSettings.cs:line 72
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 61

      '

**Comment by bubez81** [comment]
But...on a fresh install it seems working
