### ISSUE TITLE
[It broke]: Tranga is showing 'check your settings' and not reading any connections/settings

### ISSUE THREAD

**Issue by mgrimace** [C9Glax/tranga#186]
### What is broken?

When I browse to the local tranga website, it's as if there's no connection to the api. I've changed nothing but my manga no longer shows up, and there's nothing in the settings (e.g., no connections to Kavita, etc.)

### Log-output

```C#
[05/31/2024 22:23:36.378]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-36.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:37.287]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-37.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:38.869]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-38.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:39.904]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-39.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:41.396]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-41.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:43.585]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-43.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:47.585]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-47.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:23:54.583]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-23-54.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:24:08.21 ]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-24-7.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:24:34.296]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-24-34.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
[05/31/2024 22:25:26.288]        Logger | Logfile: /usr/share/tranga-api/logs/05/31/2024_22-25-26.log
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Tranga.NotificationConnectors.NotificationManagerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/NotificationConnectors/NotificationManagerJsonConverter.cs:line 31
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97
   at Tranga.GlobalBase..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/GlobalBase.cs:line 34
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 14
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 53
```

### Additional stuff

![Screenshot 2024-05-31 222427](https://github.com/C9Glax/tranga/assets/55518507/a36de6c1-34d3-47d6-a654-6f9930b12430)
![Screenshot 2024-05-31 222439](https://github.com/C9Glax/tranga/assets/55518507/cc0b599f-f7bf-4e03-8547-c2d3151423c6)

**Comment by C9Glax** [comment]
Okay the API-container is crashing on load, because there is a "`null`"-field in your `notificationConnectors.json`-file.
If you delete that file you should no longer be crashing on startup.
If you feel confident about not leaking sensitive information: Could you censor the contents of that file and reply with the contents on here?
(`at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97`)

Second there seems to be an issue with the Arguments implementation...
```
-f -c -l /usr/share/tranga-api/logs
No parameter provided for argument -l. -h for help.
```
Gonna look into that.

**Comment by C9Glax** [comment]
aea4c0c61b0c5623fb3b801582536b5b82e90557
Fixed the -l  issue hopefully

**Comment by mgrimace** [comment]
> Okay the API-container is crashing on load, because there is a "`null`"-field in your `notificationConnectors.json`-file. If you delete that file you should no longer be crashing on startup. If you feel confident about not leaking sensitive information: Could you censor the contents of that file and reply with the contents on here? (`at Tranga.TrangaSettings.LoadNotificationConnectors(GlobalBase clone) in /src/Tranga/TrangaSettings.cs:line 97`)
> 
> Second there seems to be an issue with the Arguments implementation...
> 
> ```
> -f -c -l /usr/share/tranga-api/logs
> No parameter provided for argument -l. -h for help.
> ```
> 
> Gonna look into that.

Thank you, deleting the file worked. For reference, here is the redacted file content:
```json
[{"notificationConnectorType":2,"endpoint":"https://ntfy.mydomain.com/manga"}]
```
I'll reply in the other issue re. NTFY, but I had tried to enter my NTFY details. It wasn't clear what type of auth to use, but I tried my basic auth, token, and webhook auth (which are all slightly different implementations). I'm not sure what it had ultimately landed on when it broke Tranga, but clearly I had done something wrong.

Thanks for the quick reply, and appreciate the support!

**Comment by C9Glax** [comment]
> Thank you, deleting the file worked. For reference, here is the redacted file content:
I suppose that "auth" was missing, which was an old issue fixed [here](https://github.com/C9Glax/tranga/commit/c6d0168d2f37097dd06164fb8f4524b3c0bc007a)
Other issue should also now be fixed. you had the "/manga" topic set, which didn't work previously but now should.
