### ISSUE TITLE
[It broke]: adding a new manga tranga crash

### ISSUE THREAD

**Issue by bubez81** [C9Glax/tranga#220]
### What is broken?

Hello,sorry for bordering you but today I tried to add a new manga "Solo Leveling Arise" with Mangaword, but the docker crashed with this error:
```
[08/15/2024 23:07:16.851]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-a2lsbHRoZWhlcm8yMDIw Manga: Publication Kill the Hero a2lsbHRoZWhlcm8yMDIw
[08/15/2024 23:07:16.851]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-bGF0bmFzYWdhc3Vydml2YWxvZmFzd29yZGtpbmcyMDE5 Manga: Publication Latna Saga: Survival of a Sword King bGF0bmFzYWdhc3Vydml2YWxvZmFzd29yZGtpbmcyMDE5
[08/15/2024 23:07:16.851]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-bGV2ZWx1cHdpdGh0aGVnb2RzMjAyMQ== Manga: Publication Level Up With the Gods bGV2ZWx1cHdpdGh0aGVnb2RzMjAyMQ==
[08/15/2024 23:07:16.851]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-bGltaXRicmVha2VyMjAyMA== Manga: Publication Limit Breaker bGltaXRicmVha2VyMjAyMA==
[08/15/2024 23:07:16.853]    Mangaworld | Getting new Chapters for Publication Solo Leveling: Arise c29sb2xldmVsaW5nYXJpc2UyMDI0
[08/15/2024 23:07:16.854]    Mangaworld | Getting chapters Publication Solo Leveling: Arise c29sb2xldmVsaW5nYXJpc2UyMDI0
[08/15/2024 23:07:17.179]    Mangaworld | Got 4 chapters. Publication Solo Leveling: Arise c29sb2xldmVsaW5nYXJpc2UyMDI0
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: Value could not be parsed
   at Tranga.Chapter.CompareTo(Object obj) in /src/Tranga/Chapter.cs:line 81
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.SortedMap(Buffer`1 buffer)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tranga.MangaConnectors.Mangaworld.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangaworld.cs:line 141
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 61
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 276
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Fixed in `cuttingedge`
