### ISSUE TITLE
[It broke]: Unhandled exception. System.FormatException: The input string '10 hour ago ' was not in a correct format.

### ISSUE THREAD

**Issue by absturztau-be** [C9Glax/tranga#223]
### What is broken?

Seems like the Manganato connector has troubles with parsing upload dates in form of "x hours ago" or "x days ago" since latest cutting-edge build. can't tell which manga it is specifically, since logs don't tell me

### Log-output

```C#
Unhandled exception. System.FormatException: The input string '10 hour ago ' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Convert.ToInt32(String value)
   at Tranga.MangaConnectors.Manganato.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId, String websiteUrl) in /src/Tranga/MangaConnectors/Manganato.cs:line 130
   at Tranga.MangaConnectors.Manganato.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/Manganato.cs:line 68
   at Tranga.MangaConnectors.Manganato.GetMangaFromId(String publicationId) in /src/Tranga/MangaConnectors/Manganato.cs:line 56
   at Tranga.Jobs.UpdateMetadata.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/UpdateMetadata.cs:line 27
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 276
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Should be fixed on `cuttingedge` branch, if so, close the issue or lmk

**Comment by absturztau-be** [comment]
from what i can tell, it seems to be fixed. thank you
