### ISSUE TITLE
[It broke]: Searching on MangaSee is very slow and doesnt work

### ISSUE THREAD

**Issue by ElryMoe** [C9Glax/tranga#227]
### What is broken?

i searched for "Made in Abyss" on the Tranga website like 5min ago with MangaSee selected and its still not done.

### Log-output

```C#
tranga-api  | [08/25/2024 10:22:06.986]       JobBoss | Next job in
tranga-api  | [08/25/2024 10:22:07.5  ]        Server | Listening on http://*:6531/
tranga-api  | [08/25/2024 11:24:21.938]      Mangasee | Searching Publications. Term="Made in Abyss"
tranga-api  | [08/25/2024 11:24:23.970] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:24.265]      Mangasee | Total available manga: 8350 Filtered down to: 121
tranga-api  | [08/25/2024 11:24:25.985] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:26.445]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-3x3-Eyes.jpg
tranga-api  | [08/25/2024 11:24:28.13 ] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:28.55 ]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Action-Mask.jpg
tranga-api  | [08/25/2024 11:24:28.57 ] ChromiumDownl | Waiting 0.2063793 seconds
tranga-api  | [08/25/2024 11:24:29.724] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:29.761]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Adekan.jpg
tranga-api  | [08/25/2024 11:24:29.763] ChromiumDownl | Waiting 0.2195008 seconds
tranga-api  | [08/25/2024 11:24:31.461] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:31.492]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Adu-Of-Hades.jpg
tranga-api  | [08/25/2024 11:24:31.496] ChromiumDownl | Waiting 0.2206819 seconds
tranga-api  | [08/25/2024 11:24:33.285] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:33.325]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Aekanaru.jpg
tranga-api  | [08/25/2024 11:24:33.329] ChromiumDownl | Waiting 0.2181264 seconds
tranga-api  | [08/25/2024 11:24:35.27 ] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:35.71 ]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Age-Matters.jpg
tranga-api  | [08/25/2024 11:24:35.72 ] ChromiumDownl | Waiting 0.2154148 seconds
tranga-api  | [08/25/2024 11:24:36.794] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:36.829]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Ake-No-Tobari.jpg
tranga-api  | [08/25/2024 11:24:36.831] ChromiumDownl | Waiting 0.2199826 seconds
tranga-api  | [08/25/2024 11:24:38.564] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:38.607]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Akkan-Baby.jpg
tranga-api  | [08/25/2024 11:24:38.609] ChromiumDownl | Waiting 0.2079802 seconds
tranga-api  | [08/25/2024 11:24:40.303] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:40.338]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Ane-Kurabe.jpg
tranga-api  | [08/25/2024 11:24:40.339] ChromiumDownl | Waiting 0.218519 seconds
tranga-api  | [08/25/2024 11:24:42.33 ] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:42.80 ]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Asahinagu.jpg
tranga-api  | [08/25/2024 11:24:42.82 ] ChromiumDownl | Waiting 0.2013814 seconds
tranga-api  | [08/25/2024 11:24:43.818] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:43.852]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Asobi-Asobase.jpg
tranga-api  | [08/25/2024 11:24:43.861] ChromiumDownl | Waiting 0.2151904 seconds
tranga-api  | [08/25/2024 11:24:45.630] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:45.664]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Astro-Baby.jpg
tranga-api  | [08/25/2024 11:24:45.668] ChromiumDownl | Waiting 0.2184421 seconds
tranga-api  | [08/25/2024 11:24:47.405] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:47.456]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Ayu-Mayu.jpg
tranga-api  | [08/25/2024 11:24:47.458] ChromiumDownl | Waiting 0.2007519 seconds
tranga-api  | [08/25/2024 11:24:49.140] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:49.169]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Baby-Princess.jpg
tranga-api  | [08/25/2024 11:24:49.171] ChromiumDownl | Waiting 0.2203496 seconds
tranga-api  | [08/25/2024 11:24:50.835] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:24:50.861]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Bad-Company.jpg
tranga-api  | [08/25/2024 11:24:50.864] ChromiumDownl | Waiting 0.2228124 seconds
tranga-api  | [08/25/2024 11:25:01.188] ChromiumDownl | Could not load Page:
tranga-api  | One or more errors occurred. (Timeout of 10000 ms exceeded)
tranga-api  | [08/25/2024 11:25:01.188] ChromiumDownl | Waiting 0.239924 seconds
tranga-api  | [08/25/2024 11:25:02.937] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:02.982]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Blade-Note.jpg
tranga-api  | [08/25/2024 11:25:02.983] ChromiumDownl | Waiting 0.2125494 seconds
tranga-api  | [08/25/2024 11:25:04.668] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:04.703]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Blade-Play.jpg
tranga-api  | [08/25/2024 11:25:04.707] ChromiumDownl | Waiting 0.2167734 seconds
tranga-api  | [08/25/2024 11:25:06.419] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:06.455]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Blue-Hearts.jpg
tranga-api  | [08/25/2024 11:25:06.458] ChromiumDownl | Waiting 0.2211226 seconds
tranga-api  | [08/25/2024 11:25:08.206] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:08.270]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Lan-Chi.jpg
tranga-api  | [08/25/2024 11:25:08.273] ChromiumDownl | Waiting 0.1957916 seconds
tranga-api  | [08/25/2024 11:25:10.230] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:10.364]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Shounen-no-Abyss.jpg
tranga-api  | [08/25/2024 11:25:10.386] ChromiumDownl | Waiting 0.1627016 seconds
tranga-api  | [08/25/2024 11:25:12.16 ] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:12.45 ]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Brave10-S.jpg
tranga-api  | [08/25/2024 11:25:12.47 ] ChromiumDownl | Waiting 0.2246911 seconds
tranga-api  | [08/25/2024 11:25:13.694] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:13.721]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Cafe-Cafe.jpg
tranga-api  | [08/25/2024 11:25:13.723] ChromiumDownl | Waiting 0.2206085 seconds
tranga-api  | [08/25/2024 11:25:15.401] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:25:15.439]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/temp.compsci88.com-Cage-Of-Eden.jpg
tranga-api  | [08/25/2024 11:25:15.442] ChromiumDownl | Waiting 0.221245 seconds
.....
tranga-api  | [08/25/2024 11:31:40.957]      Mangasee | Retrieved 121 publications. Term="Made in Abyss"
tranga-api  | [08/25/2024 11:31:40.960]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
tranga-api  |    at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
tranga-api  |    at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
tranga-api  |    at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
tranga-api  |    at System.IO.Stream.Write(ReadOnlySpan`1 buffer)
tranga-api  |    at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 760
```

### Additional stuff

Its prolly the same issue as #224

**Comment by ElryMoe** [comment]
It also seems to redownload it every time i search.

```
tranga-api  | [08/25/2024 11:28:22.875]      Mangasee | Searching Publications. Term="Made in Abyss"
tranga-api  | [08/25/2024 11:28:24.903] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:25.44 ]      Mangasee | Total available manga: 8350 Filtered down to: 121
tranga-api  | [08/25/2024 11:28:26.878] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:26.901]      Mangasee | Overwriting Manga eGV5ZXMxOTg3
tranga-api  | [08/25/2024 11:28:26.902] ChromiumDownl | Waiting 0.0984525 seconds
tranga-api  | [08/25/2024 11:28:28.479] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:28.492]      Mangasee | Overwriting Manga YWN0aW9ubWFzazIwMTM=
tranga-api  | [08/25/2024 11:28:28.492] ChromiumDownl | Waiting 0.0989265 seconds
tranga-api  | [08/25/2024 11:28:30.53 ] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:30.68 ]      Mangasee | Overwriting Manga YWRla2FuMjAwOA==
tranga-api  | [08/25/2024 11:28:30.69 ] ChromiumDownl | Waiting 0.0982973 seconds
tranga-api  | [08/25/2024 11:28:31.636] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:31.651]      Mangasee | Overwriting Manga YWR1b2ZoYWRlczIwMTU=
tranga-api  | [08/25/2024 11:28:31.651] ChromiumDownl | Waiting 0.0972743 seconds
tranga-api  | [08/25/2024 11:28:33.270] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:33.298]      Mangasee | Overwriting Manga YWVrYW5hcnUyMDIw
tranga-api  | [08/25/2024 11:28:33.298] ChromiumDownl | Waiting 0.0964499 seconds
tranga-api  | [08/25/2024 11:28:34.874] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:34.891]      Mangasee | Overwriting Manga YWdlbWF0dGVyczIwMTg=
tranga-api  | [08/25/2024 11:28:34.891] ChromiumDownl | Waiting 0.0976859 seconds
tranga-api  | [08/25/2024 11:28:36.420] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:36.439]      Mangasee | Overwriting Manga YWtlbm90b2JhcmkyMDE0
tranga-api  | [08/25/2024 11:28:36.439] ChromiumDownl | Waiting 0.0986774 seconds
tranga-api  | [08/25/2024 11:28:37.972] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:37.984]      Mangasee | Overwriting Manga YWtrYW5iYWJ5MjAwMQ==
tranga-api  | [08/25/2024 11:28:37.984] ChromiumDownl | Waiting 0.0984626 seconds
tranga-api  | [08/25/2024 11:28:39.513] ChromiumDownl | Page loaded.
tranga-api  | [08/25/2024 11:28:39.526]      Mangasee | Overwriting Manga YW5la3VyYWJlMjAxNA==
tranga-api  | [08/25/2024 11:28:39.526] ChromiumDownl | Waiting 0.0986495 seconds
```

**Comment by ElryMoe** [comment]
I got it a bit faster (Waiting is very fast now, but its using Chromium, so its taking 2 seconds per Image)

**Comment by ElryMoe** [comment]
Idk if you can apply the same fix for the manga image downloading for the manga search ?

**Comment by ElryMoe** [comment]
Oh it stopped and ran into an error now, so searching doesnt even work

**Comment by ElryMoe** [comment]
Using the mangasee link directly seems to work fine tho

**Comment by C9Glax** [comment]
MangaSees search **sucks**, so I use  [NeedlemanWunsch](https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm) that still needs some tuning on results. 
The issue right [here](https://github.com/C9Glax/tranga/issues/132) is exactly related, and for those that know, they will just use the link directly, like you did.
Why it broke above, is that it tried to answer the request you made, but probably after a while you refreshed the page? So it tried to answer on a closed stream.

**Comment by C9Glax** [comment]
So leave this open, until I fine tuned the parameters.

**Comment by ElryMoe** [comment]
> MangaSees search **sucks**, so I use [NeedlemanWunsch](https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm) that still needs some tuning on results. The issue right [here](https://github.com/C9Glax/tranga/issues/132) is exactly related, and for those that know, they will just use the link directly, like you did. Why it broke above, is that it tried to answer the request you made, but probably after a while you refreshed the page? So it tried to answer on a closed stream.

Yeah it could be that i closed the page, i dont remember, it prolly took so long that i refreshed the page.

Lets leave this open for Needleman improvements.

**Comment by ElryMoe** [comment]
@C9Glax just saw your pushes, its working now from what i can tell.

**Comment by C9Glax** [comment]
It is definitely working and only retrieving the top 10 search results now.
The issue is: To get the cover images we HAVE to use the ChromiumClient, because otherwise we don't get their URLs. The download itself is fast now, but loading the webpage takes a solid 2 seconds. So Mangasee will take about 20-25 seconds to load.
But definitely a lot better than before with 100s of results.

**Comment by ElryMoe** [comment]
Yes that sounds a lot better ^^On 26 Aug 2024 12:50, Glax ***@***.***> wrote:
It is definitely working and only retrieving the top 10 search results now.
The issue is: To get the cover images we HAVE to use the ChromiumClient, because otherwise we don't get their URLs. The download itself is fast now, but loading the webpage takes a solid 2 seconds. So Mangasee will take about 20-25 seconds to load.
But definitely a lot better than before with 100s of results.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On 26 Aug 2024 12:50, Glax ***@***.***> wrote:
It is definitely working and only retrieving the top 10 search results now.
The issue is: To get the cover images we HAVE to use the ChromiumClient, because otherwise we don't get their URLs. The download itself is fast now, but loading the webpage takes a solid 2 seconds. So Mangasee will take about 20-25 seconds to load.
But definitely a lot better than before with 100s of results.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On 26 Aug 2024 12:50, Glax ***@***.***> wrote:
It is definitely working and only retrieving the top 10 search results now.
The issue is: To get the cover images we HAVE to use the ChromiumClient, because otherwise we don't get their URLs. The download itself is fast now, but loading the webpage takes a solid 2 seconds. So Mangasee will take about 20-25 seconds to load.
But definitely a lot better than before with 100s of results.
