### ISSUE TITLE
[It broke]: PathTooLongException when exporting job file

### ISSUE THREAD

**Issue by MicGeb1997** [C9Glax/tranga#237]
### What is broken?

During the export of a job file, the system attempts to create a file with an excessively long path, which results in a `System.IO.PathTooLongException`.

### Log-output

```C#
[09/05/2024 16:36:48.137]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-YmlyeXV1ZW5zaG91dGFuamlrb2tvdXRlaWthbmdhZ2VraXRlaW5hZHJhZ29ua3l1dWJpc2hvdWpvbWFvdW95dXVzaGFnYWljaGFyYWJ1ZGV0YWlqaXN1cnVvaGFuYXNoaTIwMjE=.json
[09/05/2024 16:36:48.144]       JobBoss | Already Contains Job Tranga.Jobs.UpdateMetadata-YmlyeXV1ZW5zaG91dGFuamlrb2tvdXRlaWthbmdhZ2VraXRlaW5hZHJhZ29ua3l1dWJpc2hvdWpvbWFvdW95dXVzaGFnYWljaGFyYWJ1ZGV0YWlqaXN1cnVvaGFuYXNoaTIwMjE= Manga: Publication Biryuu Enshoutan ~Jikokouteikan ga Gekitei na Dragon-kyuu Bishoujo Maou o, Yuusha ga Icharabu de Taijisuru Ohanashi~ YmlyeXV1ZW5zaG91dGFuamlrb2tvdXRlaWthbmdhZ2VraXRlaW5hZHJhZ29ua3l1dWJpc2hvdWpvbWFvdW95dXVzaGFnYWljaGFyYWJ1ZGV0YWlqaXN1cnVvaGFuYXNoaTIwMjE=
[09/05/2024 16:36:48.148]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-YmlyeXV1ZW5zaG91dGFuamlrb2tvdXRlaWthbmdhZ2VraXRlaW5hZHJhZ29ua3l1dWJpc2hvdWpvbWFvdW95dXVzaGFnYWljaGFyYWJ1ZGV0YWlqaXN1cnVvaGFuYXNoaTIwMjE= Manga: Publication Biryuu Enshoutan ~Jikokouteikan ga Gekitei na Dragon-kyuu Bishoujo Maou o, Yuusha ga Icharabu de Taijisuru Ohanashi~ YmlyeXV1ZW5zaG91dGFuamlrb2tvdXRlaWthbmdhZ2VraXRlaW5hZHJhZ29ua3l1dWJpc2hvdWpvbWFvdW95dXVzaGFnYWljaGFyYWJ1ZGV0YWlqaXN1cnVvaGFuYXNoaTIwMjE=
[09/05/2024 16:36:48.254]       JobBoss | Next job in -27.14:26:58.1264518 Tranga.Jobs.DownloadNewChapters-aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.359]      MangaDex | Getting new Chapters for Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.363]      MangaDex | Getting chapters Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.387]      MangaDex | Got 18 chapters. Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.392]      MangaDex | Checking for duplicates Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.420]      MangaDex | 1 new chapters. Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.424]      MangaDex | Copy cover Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.429]      MangaDex | Cover exists Publication I, a Level 9999 Blacksmith Who Was Told That "Blacksmithing Is Suitable for a Small Fry lololol" Was Expelled From the Guild, so I Changed My Job to an Adventurer - I Will Live Happily in the Guild While being Unrivaled with the Strongest Weapons! aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=
[09/05/2024 16:36:48.434]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=.json
Unhandled exception. System.IO.PathTooLongException: The path '/usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-aWFsZXZlbGJsYWNrc21pdGh3aG93YXN0b2xkdGhhdGJsYWNrc21pdGhpbmdpc3N1aXRhYmxlZm9yYXNtYWxsZnJ5bG9sb2xvbHdhc2V4cGVsbGVkZnJvbXRoZWd1aWxkc29pY2hhbmdlZG15am9idG9hbmFkdmVudHVyZXJpd2lsbGxpdmVoYXBwaWx5aW50aGVndWlsZHdoaWxlYmVpbmd1bnJpdmFsZWR3aXRodGhlc3Ryb25nZXN0d2VhcG9uczIwMjM=.json' is too long, or a component of the specified path is too long.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Tranga.Jobs.JobBoss.UpdateJobFile(Job job, String oldFile) in /src/Tranga/Jobs/JobBoss.cs:line 212
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 277
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 73
```

**Comment by C9Glax** [comment]
What is that Manga title 💀 
But yea, Linux Filename Character Limit is 255, and 264 (the base64 encoded string) is longer than 255.
So congrats on finding this edgecase

**Comment by C9Glax** [comment]
Well I created a fix, but forgot to push from my main machine, so it's gotta wait a week.

**Comment by C9Glax** [comment]
Fixed in `cuttingedge`.
