### ISSUE TITLE
[It broke]: CuttingEdge unable to start

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#238]
### What is broken?

Pulled the latest version of the cutting edge docker image to maintain my stack which I haven't touched in weeks and found Tranga unable to start due to this error: 
![image](https://github.com/user-attachments/assets/2a746a2c-f295-44e3-8370-1f22ba702c16)

### Log-output

```C#
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 26
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 26
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 26
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 26
Unhandled exception. System.IO.IOException: The file '/usr/share/tranga-api/logs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 26
```

**Comment by C9Glax** [comment]
Ah oooold bug, just delete the file "logs" in your settings directory. It should be a directory.
