### ISSUE TITLE
[It broke]: Cuttingedge error

### ISSUE THREAD

**Issue by BijuuKrunos** [C9Glax/tranga#249]
### What is broken?

Tranga does not to get up and running anymore.
Running in a K3s Cluster.
Using cuttingedge.

### Log-output

```C#
[09/16/2024 06:41:29.68 ]       JobBoss | Adding Tranga.Jobs.DownloadNewChapters-c3BhcmVtZWdyZWF0bG9yZDIwMjM=.json
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Tranga.MangaConnectors.MangaConnectorJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/MangaConnectors/MangaConnectorJsonConverter.cs:line 43
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Tranga.Jobs.JobJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/Jobs/JobJsonConverter.cs:line 44
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Tranga.Jobs.JobBoss.LoadJobsList(HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 154
   at Tranga.Jobs.JobBoss..ctor(GlobalBase clone, HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 15
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 31
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 67
```

**Comment by C9Glax** [comment]
Looks to me like one of the job-files has issues deserializing. I am adding more logging to see what is going on.

**Comment by BijuuKrunos** [comment]
`Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Tranga.MangaConnectors.MangaConnectorJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/MangaConnectors/MangaConnectorJsonConverter.cs:line 43
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Tranga.Jobs.JobJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/Jobs/JobJsonConverter.cs:line 44
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Tranga.Jobs.JobBoss.LoadJobsList(HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 154
   at Tranga.Jobs.JobBoss..ctor(GlobalBase clone, HashSet`1 connectors) in /src/Tranga/Jobs/JobBoss.cs:line 15
   at Tranga.Tranga..ctor(Logger logger, TrangaSettings settings) in /src/Tranga/Tranga.cs:line 31
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 67`

mhh maybe i am blind but i dont see a difference from before. using image_pull_policy = "IfNotPresent" so should be the newest after restart. mhh

**Comment by C9Glax** [comment]
Can you check manually what hash your current version has?
It should be `sha256:25075d9c70e90b744d6803892cf00da7d651818a0934e7d9a5cd5937827e7b79` to be the actually newest version.
![image](https://github.com/user-attachments/assets/dee7a486-ac6e-4b35-b1eb-94031c8e5d45)
Because it looks to me that it is not the latest version, especially because I moved a lot of code around...

**Comment by C9Glax** [comment]
Okay this is a very different error now 👍🏼 
Before it seemed that it had troubles starting up, deserializing what we already had, now it is erroring on retrieving from website.

**Comment by C9Glax** [comment]
It's building now, so probably 5 minutes. You can check https://github.com/C9Glax/tranga/tree/cuttingedge for when the checkmark appears 
![image](https://github.com/user-attachments/assets/67e1b1e8-9c8e-46ac-9213-31fb0330b523)

**Comment by BijuuKrunos** [comment]
thanks this seems to work again, but now if i go to my tranga website and connect to the api, all saved mangas are 4-6 times there. for example: 
![image](https://github.com/user-attachments/assets/7bc4c698-99ce-4dfc-ac0c-54257f7610eb)

I am currently using the latest on the tranga-website because in cutting edge i get:
2024/09/16 18:06:53 [emerg] 1#1: host not found in upstream "tranga-api" in /etc/nginx/conf.d/default.conf:15
nginx: [emerg] host not found in upstream "tranga-api" in /etc/nginx/conf.d/default.conf:15
as error, could it be because of this?

thanks for helping ^^

**Comment by C9Glax** [comment]
hmm my uneducated guess is that with the recent changes of how I handle Filenames see [here](https://github.com/C9Glax/tranga/issues/237), it adds copies, which sucks ;_;
It shouldn't do it for newly added Manga, but old ones will probably now all get duplicates from what I have seen :/
What *probably* would be the easiest fix, is to write down all the Manga you have, and then remove them all and re-add them...

**Comment by C9Glax** [comment]
Oh also: sometimes the frontend will mistakenly display the same Manga twice.

**Comment by BijuuKrunos** [comment]
would this not be a problem for everyone who is updating to the newest cuttingedge version? Is there no way to deduplicate it ?

**Comment by C9Glax** [comment]
Haven't really found the issue why it is doing it...

**Comment by C9Glax** [comment]
Ok found it. Here's the way to do it right now, if you already have duplicates:
1. Stop tranga-api
2. Go to the settings folder -> jobs
3. Delete all the files that have a unix timestamp as name (so `...-123456234.json`)
You should now have files left with `...-DownloadNewChapter.json`
4. Pull latest image and start, it should replace the old files.

**Comment by C9Glax** [comment]
That is if I can convince Github to build the image

**Comment by C9Glax** [comment]
There we go. It's built.

**Comment by BijuuKrunos** [comment]
because the volume where the jobs folder is on, is not that easy to access while the pod is down, i deleted the files while it was running, after deleting only the files with a timestamp in the end the folder was empty, after restarting 1/3 was missing and 2 were dupplicates. think i should delete it completely and put them in again by hand, to get rid of this xD.

**Comment by C9Glax** [comment]
Dangit, sorry about that... 
I think thst this solves everything in here?

**Comment by BijuuKrunos** [comment]
I think i can get rid of the rest errors myself, currently tranga redownloads some of the mangas, i will wait until he is finish and clean it up afterwards, but this could be a new problem, because he is redownloading mangas where i am 100% sure, that i am using the same download page as last time. mhhh

Could it be maybe a problem on the hosting sites? that they changed the description or title and its now redownloading it again after complete deletion and reapplying on tranga-api?

**Comment by C9Glax** [comment]
Duplicate chapters? Or entirely new folders?

**Comment by BijuuKrunos** [comment]
new folders

**Comment by BijuuKrunos** [comment]
could it be that you fixed a problem with some symbols like ' ?
for example:
Old Title: Trash of the Count&#039;s Family | Academy&rsquo;s Genius Swordmaster
New Title: Trash of the Count's Family | Academy’s Genius Swordmaster

**Comment by C9Glax** [comment]
Oh yes.
So what happened probably: The foldernames are created once when the Manga is added. And because you re-added them, the "name" changed, so it created a new folder.

**Comment by C9Glax** [comment]
One day ™️ I am gonna add a fuzzy search for something like this, which would be accesible through the frontend, so if Tranga thinks something already exists, it will give you a choice to select either or both.
But, that is faaaar in the future.

**Comment by BijuuKrunos** [comment]
ok than i will wait until tranga is finish and fix it. thanks for helping :)
