### ISSUE TITLE
[It broke]: Server Error

### ISSUE THREAD

**Issue by Nas-77** [C9Glax/tranga#252]
### What is broken?

I'm not sure what this is about just keep seeing this error when going through the logs.

### Log-output

```C#
[09/18/2024 16:03:49.68 ]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-638621368324213761.json
[09/18/2024 16:03:49.75 ]       JobBoss | Next job in 00:21:32.4385148 Tranga.Jobs.DownloadNewChapters-638622402701460288
[09/18/2024 16:05:55.743]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Connection reset by peer.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 753
[09/18/2024 16:05:55.742]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Connection reset by peer.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 753
[09/18/2024 16:05:55.753]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Connection reset by peer.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 753
[09/18/2024 16:05:55.759]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 753
[09/18/2024 16:05:55.759]        Server | System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Tranga.Server.SendResponse(HttpStatusCode statusCode, HttpListenerResponse response, Object content) in /src/Tranga/Server.cs:line 753
```

**Comment by C9Glax** [comment]
It's pretty normal.
Basically the user has requested a resource (in this case an image), and then closed the connection (website).
If you are requesting a lot of covers for example, it has to transfer a lot of data, and it might not be done before you are done with what you were doing, and then closing the site.
So not an Error per-se
