### ISSUE TITLE
[It broke]: Tranga-API crashes on launch after update

### ISSUE THREAD

**Issue by Charles-Em** [C9Glax/tranga#263]
### What is broken?

Hello,

I just updates tranga after a very long time of using the same version and it crashes on launch after update :'(

Something about "Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually"

Will try to look what it could be, but currently stuck.

### Log-output

```C#
date	stream	content
2024/10/14 09:30:01	stdout	[10/14/2024 07:30:01.972]        Server | Listening on http://*:6531/
2024/10/14 09:30:02	stderr	Unhandled exception. System.TypeInitializationException: The type initializer for 'Tranga.MangaConnectors.ChromiumDownloadClient' threw an exception.
2024/10/14 09:30:02	stderr	 ---> System.AggregateException: One or more errors occurred. (Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually)
2024/10/14 09:30:02	stderr	 ---> System.IO.FileNotFoundException: Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually
2024/10/14 09:30:02	stderr	   at PuppeteerSharp.Launcher.ResolveExecutablePathAsync() in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 243
2024/10/14 09:30:02	stderr	File name: '/publish/.local-chromium/Linux-1069273/chrome-linux/chrome'
2024/10/14 09:30:02	stderr	   at PuppeteerSharp.Launcher.GetOrFetchBrowserExecutableAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 200
2024/10/14 09:30:02	stderr	   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 51
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.ChromiumDownloadClient.StartBrowser() in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 17
2024/10/14 09:30:02	stderr	   --- End of inner exception stack trace ---
2024/10/14 09:30:02	stderr	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2024/10/14 09:30:02	stderr	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.ChromiumDownloadClient..cctor() in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 11
2024/10/14 09:30:02	stderr	   --- End of inner exception stack trace ---
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.ChromiumDownloadClient.MakeRequestBrowser(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 44
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.ChromiumDownloadClient.MakeRequestInternal(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 37
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.DownloadClient.MakeRequest(String url, RequestType requestType, String referrer, String clickButton) in /src/Tranga/MangaConnectors/DownloadClient.cs:line 38
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.MangaLife.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaLife.cs:line 133
2024/10/14 09:30:02	stderr	   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 58
2024/10/14 09:30:02	stderr	   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
2024/10/14 09:30:02	stderr	   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
2024/10/14 09:30:02	stderr	   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 268
2024/10/14 09:30:02	stderr	   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by Charles-Em** [comment]
update
deleted all my jobs (after backing them up) : doesn't crash
recopied all the jobs by groups and there is no crash after readding them all

Will see what happens when the next planned scanned triggers

**Comment by C9Glax** [comment]
Log output indicated chromium not being installed.
This looks to be only triggered once a Job was started, so will probably fail again.

Can you run `docker exec -it tranga-api chromium --version`

**Comment by C9Glax** [comment]
Also `/publish/.local-chromium` doesn't exist anymore, so I don't know what version of Tranga you are running...

**Comment by Charles-Em** [comment]
Ok, will do + delete and recreate the docker, may have been a problem while grabbign the latest version.
Synology has done this to em a few times in the past
