### ISSUE TITLE
[It broke]: Tranga broked

### ISSUE THREAD

**Issue by BijuuKrunos** [C9Glax/tranga#272]
### What is broken?

Always get the error from below, i am too blind to see what manga does it cause, have more than one from ManhuaPlus. The Log before this entry is always something different, so for me its random when does it happen while startup.

Using "image = "glax/tranga-api:latest"" with "image_pull_policy = "Always""

thx for helping :)

### Log-output

```C#
Unhandled exception. System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at Tranga.MangaConnectors.ManhuaPlus.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId, String websiteUrl) in /src/Tranga/MangaConnectors/ManhuaPlus.cs:line 111
   at Tranga.MangaConnectors.ManhuaPlus.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/ManhuaPlus.cs:line 66
   at Tranga.MangaConnectors.ManhuaPlus.GetMangaFromId(String publicationId) in /src/Tranga/MangaConnectors/ManhuaPlus.cs:line 56
   at Tranga.Jobs.UpdateMetadata.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/UpdateMetadata.cs:line 27
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 268
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Okay so what is going wrong, is that one of the Manga does not have a "created" tag, which is on the left here:
![image](https://github.com/user-attachments/assets/4f53c882-ce30-46ef-a277-e9d53dbb2035)
I am going to just put a default year for cases where this happens, and put it on the `cuttingedge` branch, should be up in 20-30 minutes.

**Comment by C9Glax** [comment]
Just replace the docker image tag with `cuttingedge` and pull

**Comment by BijuuKrunos** [comment]
Thanks, updated and it looks better now. :)
