### ISSUE TITLE
[It broke]: tranga-api continuos restarting 

### ISSUE THREAD

**Issue by Nikibasso94** [C9Glax/tranga#293]
### What is broken?

Tranga-api continuos restarting,
I try the lastet version and the cuttingedge but is the same problem

### Log-output

```C#
[12/10/2024 11:31:31.324]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911342316 Manga: Publication Death March kara Hajimaru Isekai Kyousoukyoku 638694270911342316
[12/10/2024 11:31:31.324]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911349760 Manga: Publication Tokyo Ghoul:re 638694270911349760
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911370871 Manga: Publication Exorcist wo Otosenai 638694270911370871
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911379823 Manga: Publication The Dark Magician Transmigrates After 66666 Years 638694270911379823
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911395508 Manga: Publication Solo Leveling: Arise 638694270911395508
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911403334 Manga: Publication The Reincarnated Inferior Magic Swordsman 638694270911403334
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911445359 Manga: Publication Gaikotsu Kishi-sama Tadaima Isekai e o Dekake-chuu 638694270911445359
[12/10/2024 11:31:31.325]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911454047 Manga: Publication Tsuki ga Michibiku Isekai Douchuu 638694270911454047
[12/10/2024 11:31:31.326]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270911471107 Manga: Publication Arifureta Shokugyou de Sekai Saikyou 638694270911471107
[12/10/2024 11:31:31.331]        Server | Listening on http://*:6531/
[12/10/2024 11:31:31.334]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911698772-41.json
[12/10/2024 11:31:31.335]    Mangaworld | Copy cover Publication The Reincarnated Inferior Magic Swordsman 638694270911698772
[12/10/2024 11:31:32.228]    Mangaworld | Cover exists Publication The Reincarnated Inferior Magic Swordsman 638694270911698772
[12/10/2024 11:31:32.228]        Tranga | {
  "downloadLocation": "/Manga",
  "workingDirectory": "/usr/share/tranga-api",
  "apiPortNumber": 6531,
  "userAgent": "Tranga (Unix; x64) / 1.0",
  "aprilFoolsMode": true,
  "version": 2,
  "requestLimits": {
    "MangaInfo": 250,
    "MangaDexFeed": 250,
    "MangaDexImage": 40,
    "MangaImage": 60,
    "MangaCover": 250,
    "Default": 60
  },
  "bufferLibraryUpdates": false,
  "bufferNotifications": false
}
[12/10/2024 11:31:32.229]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911698772-41.json
[12/10/2024 11:31:32.229]    Mangaworld | Retrieving chapter-info Chapter The Reincarnated Inferior Magic Swordsman 638694270911698772 41  Publication The Reincarnated Inferior Magic Swordsman 638694270911698772
[12/10/2024 11:31:32.330]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-638694270862773890 Manga: Publication DanMachi 638694270862773890
[12/10/2024 11:31:32.562]    Mangaworld | Downloading Images for /Manga/The Reincarnated Inferior Magic Swordsman/The Reincarnated Inferior Magic Swordsman - Vol.03 Ch.41.cbz
[12/10/2024 11:31:32.837]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638694270911698772-41 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270911698772 41 
[12/10/2024 11:31:32.838] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638694270911698772-41 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270911698772 41 
[12/10/2024 11:31:32.839]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911698772-41.json
[12/10/2024 11:31:34.576]       JobBoss | Next job in -20067.11:31:34.5765488 Tranga.Jobs.DownloadChapter-638694270911962509-40
[12/10/2024 11:31:34.677]    Mangaworld | Copy cover Publication The Reincarnated Inferior Magic Swordsman 638694270911962509
[12/10/2024 11:31:34.677]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911962509-40.json
[12/10/2024 11:31:34.678]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911962509-40.json
[12/10/2024 11:31:34.949]    Mangaworld | Cover exists Publication The Reincarnated Inferior Magic Swordsman 638694270911962509
[12/10/2024 11:31:34.949]    Mangaworld | Retrieving chapter-info Chapter The Reincarnated Inferior Magic Swordsman 638694270911962509 40  Publication The Reincarnated Inferior Magic Swordsman 638694270911962509
[12/10/2024 11:31:35.98 ]    Mangaworld | Downloading Images for /Manga/The Reincarnated Inferior Magic Swordsman/The Reincarnated Inferior Magic Swordsman - Vol.03 Ch.40.cbz
[12/10/2024 11:31:35.229]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638694270911962509-40 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270911962509 40 
[12/10/2024 11:31:35.229] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638694270911962509-40 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270911962509 40 
[12/10/2024 11:31:35.229]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270911962509-40.json
[12/10/2024 11:31:35.291]       JobBoss | Next job in -20067.11:31:35.2911322 Tranga.Jobs.DownloadChapter-638694270912000788-1535
[12/10/2024 11:31:35.391]    Mangaworld | Copy cover Publication Martial Peak 638694270912000788
[12/10/2024 11:31:35.391]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912000788-1535.json
[12/10/2024 11:31:35.392]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912000788-1535.json
[12/10/2024 11:31:36.161]    Mangaworld | Cover exists Publication Martial Peak 638694270912000788
[12/10/2024 11:31:36.161]    Mangaworld | Retrieving chapter-info Chapter Martial Peak 638694270912000788 1535  Publication Martial Peak 638694270912000788
[12/10/2024 11:31:38.230]    Mangaworld | Downloading Images for /Manga/Martial Peak/Martial Peak - Vol.0 Ch.1535.cbz
[12/10/2024 11:31:38.298]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638694270912000788-1535 Chapter: Chapter Martial Peak 638694270912000788 1535 
[12/10/2024 11:31:38.298] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638694270912000788-1535 Chapter: Chapter Martial Peak 638694270912000788 1535 
[12/10/2024 11:31:38.298]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912000788-1535.json
[12/10/2024 11:31:38.299]       JobBoss | Next job in -20067.11:31:38.2989784 Tranga.Jobs.DownloadChapter-638694270912057275-39
[12/10/2024 11:31:38.399]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912057275-39.json
[12/10/2024 11:31:38.399]    Mangaworld | Copy cover Publication The Reincarnated Inferior Magic Swordsman 638694270912057275
[12/10/2024 11:31:38.400]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912057275-39.json
[12/10/2024 11:31:40.298]    Mangaworld | Cover exists Publication The Reincarnated Inferior Magic Swordsman 638694270912057275
[12/10/2024 11:31:40.298]    Mangaworld | Retrieving chapter-info Chapter The Reincarnated Inferior Magic Swordsman 638694270912057275 39  Publication The Reincarnated Inferior Magic Swordsman 638694270912057275
[12/10/2024 11:31:40.466]    Mangaworld | Downloading Images for /Manga/The Reincarnated Inferior Magic Swordsman/The Reincarnated Inferior Magic Swordsman - Vol.03 Ch.39.cbz
[12/10/2024 11:31:40.556]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638694270912057275-39 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270912057275 39 
[12/10/2024 11:31:40.556] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638694270912057275-39 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270912057275 39 
[12/10/2024 11:31:40.556]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912057275-39.json
[12/10/2024 11:31:40.557]       JobBoss | Next job in -20067.11:31:40.5571214 Tranga.Jobs.DownloadChapter-638694270912094617-42
[12/10/2024 11:31:40.657]    Mangaworld | Copy cover Publication The Reincarnated Inferior Magic Swordsman 638694270912094617
[12/10/2024 11:31:40.657]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912094617-42.json
[12/10/2024 11:31:40.658]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912094617-42.json
[12/10/2024 11:31:40.905]    Mangaworld | Cover exists Publication The Reincarnated Inferior Magic Swordsman 638694270912094617
[12/10/2024 11:31:40.906]    Mangaworld | Retrieving chapter-info Chapter The Reincarnated Inferior Magic Swordsman 638694270912094617 42  Publication The Reincarnated Inferior Magic Swordsman 638694270912094617
[12/10/2024 11:31:40.907] HttpDownloadC | Waiting 0.5601102 seconds
[12/10/2024 11:31:41.621]    Mangaworld | Downloading Images for /Manga/The Reincarnated Inferior Magic Swordsman/The Reincarnated Inferior Magic Swordsman - Vol.03 Ch.42.cbz
[12/10/2024 11:31:41.751]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638694270912094617-42 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270912094617 42 
[12/10/2024 11:31:41.751] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638694270912094617-42 Chapter: Chapter The Reincarnated Inferior Magic Swordsman 638694270912094617 42 
[12/10/2024 11:31:41.751]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638694270912094617-42.json
[12/10/2024 11:31:41.752]       JobBoss | Next job in -7.18:59:53.4440010 Tranga.Jobs.DownloadNewChapters-638694270898871586
[12/10/2024 11:31:42.426]    Mangaworld | Getting new Chapters for Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:42.426]    Mangaworld | Getting chapters Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:42.426] HttpDownloadC | Waiting 0.1940862 seconds
[12/10/2024 11:31:45.144]    Mangaworld | Got 433 chapters. Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:45.155]    Mangaworld | Checking for duplicates Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.265]    Mangaworld | 0 new chapters. Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.268]    Mangaworld | Copy cover Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.357]    Mangaworld | Cover exists Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.357]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-638694270898871586.json
[12/10/2024 11:31:56.358]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-638694270898871586.json
[12/10/2024 11:31:56.358]       JobBoss | Already Contains Job Tranga.Jobs.UpdateMetadata-638694270898871586 Manga: Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.358]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-638694270898871586 Manga: Publication Boku no Hero Academia 638694270898871586
[12/10/2024 11:31:56.862]       JobBoss | Next job in -22:47:04.6165112 Tranga.Jobs.DownloadNewChapters-638694270863842183
[12/10/2024 11:31:57.829]    Mangaworld | Getting new Chapters for Publication Bleach 638694270863842183
[12/10/2024 11:31:57.829]    Mangaworld | Getting chapters Publication Bleach 638694270863842183
[12/10/2024 11:31:58.373]    Mangaworld | Got 705 chapters. Publication Bleach 638694270863842183
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: Value could not be parsed.
	VolumeNumber: '15' ChapterNumber: ''
	Other-VolumeNumber: '39' Other-ChapterNumber: '335'
	Chapter Bleach 638694270863842183  
	Chapter Bleach 638694270863842183 335 
   at Tranga.Chapter.CompareTo(Object obj) in /src/Tranga/Chapter.cs:line 78
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys_DefaultComparer_NoNext_Ascending(Int32 index1, Int32 index2)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.SortedMap(Buffer`1 buffer)
   at System.Linq.OrderedEnumerable`1.Fill(Buffer`1 buffer, Span`1 destination)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tranga.MangaConnectors.Mangaworld.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangaworld.cs:line 141
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 58
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 279
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 75
[12/10/2024 11:32:39.431]        Logger | Logfile: /usr/share/tranga-api/logs/12/10/2024_11-32-38.log
[12/10/2024 11:32:40.385]       LunaSea | Creating notificationConnector LunaSea
[12/10/2024 11:32:40.393]        Kavita | Creating libraryConnector Kavita
[12/10/2024 11:32:40.400]        Tranga | 

 _______                                   
|_     _|.----..---.-..-----..-----..---.-.
  |   |  |   _||  _  ||     ||  _  ||  _  |
  |___|  |__|  |___._||__|__||___  ||___._|
                             |_____|       


[12/10/2024 11:32:40.631]       JobBoss | Adding Tranga.Jobs.DownloadNewChapters-638693541871082837.json
[12/10/2024 11:32:40.717]       JobBoss | Adding Job Tranga.Jobs.DownloadNewChapters-638694271607074567 Manga: Publication DanMachi 638694271607074567
[12/10/2024 11:32:40.718]       JobBoss | Added Tranga.Jobs.DownloadNewChapters-638694271607074567 Manga: Publication DanMachi 638694271607074567
[12/10/2024 11:32:40.719]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-638694271607074567.json
```

**Comment by C9Glax** [comment]
This is the problem:
![image](https://github.com/user-attachments/assets/a1772bab-834a-4396-982d-6c8d246202be)
The Chapternumber is preceeded by a `-` which is not standard for the site and thus messes with the number-parsing.

**Comment by C9Glax** [comment]
Should be fixed on `cuttingedge`?

**Comment by C9Glax** [comment]
Closing as stale
