### ISSUE TITLE
[It broke]: AsuraToon connector timing out

### ISSUE THREAD

**Issue by theAlevan** [C9Glax/tranga#296]
### What is broken?

The AsuraToon connector is timing our with the following log message:

### Log-output

```C#
[12/13/2024 11:05:02.40 ]     AsuraToon | Copy cover Publication Bad Born Blood 638696744328545125
[12/13/2024 11:05:02.41 ]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638696744328545125-1.json
[12/13/2024 11:05:02.45 ]     AsuraToon | Cover exists Publication Bad Born Blood 638696744328545125
[12/13/2024 11:05:02.45 ]     AsuraToon | Retrieving chapter-info Chapter Bad Born Blood 638696744328545125 1  Publication Bad Born Blood 638696744328545125
[12/13/2024 11:05:02.45 ] HttpDownloadC | Waiting 0.7096204 seconds
[12/13/2024 11:05:02.832] HttpDownloadC | Waiting 0.9999918 seconds
[12/13/2024 11:10:02.95 ]       JobBoss | Tranga.Jobs.DownloadChapter-638696744328545125-1 Chapter: Chapter Bad Born Blood 638696744328545125 1  inactive for more than 5 minutes. Cancelling.
[12/13/2024 11:10:02.95 ] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638696744328545125-1 Chapter: Chapter Bad Born Blood 638696744328545125 1 
[12/13/2024 11:10:02.195]       JobBoss | Removing Tranga.Jobs.DownloadChapter-638696744328545125-1 Chapter: Chapter Bad Born Blood 638696744328545125 1 
[12/13/2024 11:10:02.195] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-638696744328545125-1 Chapter: Chapter Bad Born Blood 638696744328545125 1 
[12/13/2024 11:10:02.195]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-638696744328545125-1.json
```

**Comment by yacob841** [comment]
Same. I was able to search and add a few but only 3 chapters downloaded before I started getting timeouts and can't search anymore.

**Comment by C9Glax** [comment]
Ok got a first StackTrace:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Tranga.MangaConnectors.AsuraToon.ParseImageUrlsFromHtml(String mangaUrl) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 213
   at Tranga.MangaConnectors.AsuraToon.DownloadChapter(Chapter chapter, ProgressToken progressToken) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 191
   at Tranga.Jobs.DownloadChapter.<ExecuteReturnSubTasksInternal>b__8_0() in /src/Tranga/Jobs/DownloadChapter.cs:line 35
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
Seems like AsuraToon does not serve static sites. Switching to ChromiumDownloadClient...

**Comment by C9Glax** [comment]
Should be fixed on `cuttingedge` tag/branch, let me know if it is still broken.

**Comment by yacob841** [comment]
I switched to cuttingedge and the added sites were able to download but the search is still not working.

Sometimes I get this:
```
[12/14/2024 06:48:08.546]     AsuraToon | Searching Publications. Term="Dragon"
[12/14/2024 06:48:10.560] ChromiumDownl | Page loaded.
[12/14/2024 06:48:13.334] ChromiumDownl | Page loaded.
[12/14/2024 06:48:13.558]     AsuraToon | Saving cover to /usr/share/tranga-api/imageCache/gg.asuracomic.net-dragon-devouring-mage-cc4eca9f.webp
```
But nothing shows up on the site, and still has a greyed out search.

Other times I just get this:
```
[12/14/2024 06:54:20.950]     AsuraToon | Searching Publications. Term="Dragon"
[12/14/2024 06:54:22.429] ChromiumDownl | Page loaded.
[12/14/2024 06:54:24.841] ChromiumDownl | Page loaded.
```
And again, still a greyed out search.

**Comment by theAlevan** [comment]
The initial problem of downloading seems to be fixed.

The search seems not fully functioning, what the only way I can add something is to copy and paste the title exatly from the AsuraToon website.

**Comment by C9Glax** [comment]
Okay going to look into that then

**Comment by C9Glax** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tranga.MangaConnectors.AsuraToon.ParsePublicationsFromHtml(HtmlDocument document) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 58
   at Tranga.MangaConnectors.AsuraToon.GetManga(String publicationTitle) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 32
   at Tranga.Server.HandleGet(HttpListenerRequest request, HttpListenerResponse response) in /src/Tranga/Server.cs:line 159
   at Tranga.Server.HandleRequest(HttpListenerContext context) in /src/Tranga/Server.cs:line 75
   at Tranga.Server.<>c__DisplayClass4_0.<Listen>b__0() in /src/Tranga/Server.cs:line 51
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
``` 
Seems like it doesn't like empty Searchresults

**Comment by C9Glax** [comment]
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Tranga.MangaConnectors.AsuraToon.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId, String websiteUrl) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 109
   at Tranga.MangaConnectors.AsuraToon.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 52
   at Tranga.MangaConnectors.AsuraToon.ParsePublicationsFromHtml(HtmlDocument document) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 66
   at Tranga.MangaConnectors.AsuraToon.GetManga(String publicationTitle) in /src/Tranga/MangaConnectors/AsuraToon.cs:line 32
   at Tranga.Server.HandleGet(HttpListenerRequest request, HttpListenerResponse response) in /src/Tranga/Server.cs:line 159
   at Tranga.Server.HandleRequest(HttpListenerContext context) in /src/Tranga/Server.cs:line 75
   at Tranga.Server.<>c__DisplayClass4_0.<Listen>b__0() in /src/Tranga/Server.cs:line 51
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

In general it seems there is a lot of missing values... 😸

**Comment by C9Glax** [comment]
It's building and should be fixed? Tried it myself with some searches, and returned the expected result!

**Comment by theAlevan** [comment]
Tested and it seems ok.
