### ISSUE TITLE
[It broke]: Failed to launch browser! chrome_crashpad_handler: --database is required

### ISSUE THREAD

**Issue by vmoriaux** [C9Glax/tranga#300]
### What is broken?

Since December 5th, according to the logs, the Tranga-API container fails to start. I have tried to restore a backup of my volume (mounted in /usr/share/tranga-api) but the issue remains.
I also just updated the container image to latest, same result. And there don't seem to be a versioned tag available on DockerHub, so I can't roll back to a prior version 

### Log-output

```C#
[12/14/2024 09:56:30.109]        Logger | Logfile: /usr/share/tranga-api/logs/12/14/2024_9-56-30.log
[12/14/2024 09:56:30.251]        Tranga | 
 _______                                   
|_     _|.----..---.-..-----..-----..---.-.
  |   |  |   _||  _  ||     ||  _  ||  _  |
  |___|  |__|  |___._||__|__||___  ||___._|
                             |_____|       
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[14:14:1214/095630.319808:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser! chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[14:14:1214/095630.319808:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
   at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 83
   at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 77
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 110
   at Tranga.MangaConnectors.ChromiumDownloadClient.StartBrowser(Logger logger) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 19
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Tranga.MangaConnectors.ChromiumDownloadClient..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 58
   at Tranga.MangaConnectors.Mangasee..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/Mangasee.cs:line 16
   at Tranga.Tranga..ctor(Logger logger) in /src/Tranga/Tranga.cs:line 18
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 49
```

**Comment by C9Glax** [comment]
Looking at this https://github.com/hardkoded/puppeteer-sharp/issues/2633 this should be a permission issue, gonna push a fix to `cuttingedge` in a minute

**Comment by C9Glax** [comment]
Image is building, please pull `cuttingedge` and let me know if the issue persists!

**Comment by vmoriaux** [comment]
This does appear to have fixed my issue, thanks. The container is now starting and stays up.

**Comment by vmoriaux** [comment]
Nevermind, still the same exception

**Comment by C9Glax** [comment]
hmmm.
Can you share some setup information?
Docker, which image-tag, other virtualization, ARM/x86

**Comment by vmoriaux** [comment]
Apologies once again. When restoring the settings, I also restored the compose file, so it reverted to the "latest" instead of "cuttingedge". Switch it again, and it works again. I think I need more sleep !

**Comment by C9Glax** [comment]
All good! Happy it works, and will merge in due time 👍🏼
