### ISSUE TITLE
[It broke]: Unable to pull 'Helck' from Mangadex

### ISSUE THREAD

**Issue by YuuichiLV** [C9Glax/tranga#307]
### What is broken?

Mangadex pulling Helck causes loop with crashes. Even tried creating a new docker and just added Helck and still failed.

### Log-output

```C#
12/24/2024 19:28:33.327]      MangaDex | Getting new Chapters for Publication Helck 638706653099147147
[12/24/2024 19:28:33.327]      MangaDex | Getting chapters Publication Helck 638706653099147147
[12/24/2024 19:28:33.386] HttpDownloadC | Waiting 0.2232519 seconds
[12/24/2024 19:28:33.664] HttpDownloadC | Waiting 0.2103226 seconds
[12/24/2024 19:28:33.908]      MangaDex | Got 244 chapters. Publication Helck 638706653099147147
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: Value could not be parsed.
	VolumeNumber: '10' ChapterNumber: '86'
	Other-VolumeNumber: '7' Other-ChapterNumber: '61.2.5'
	Chapter Helck 638706653099147147 86 
	Chapter Helck 638706653099147147 61.2.5 
   at Tranga.Chapter.CompareTo(Object obj) in /src/Tranga/Chapter.cs:line 78
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys_DefaultComparer_NoNext_Ascending(Int32 index1, Int32 index2)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1 keys, Comparison`1 comparer, Int32 i, Int32 j)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.SortedMap(Buffer`1 buffer)
   at System.Linq.OrderedEnumerable`1.Fill(Buffer`1 buffer, Span`1 destination)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tranga.MangaConnectors.MangaDex.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaDex.cs:line 256
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 58
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 279
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 75
```

### Additional stuff

N/A

**Comment by C9Glax** [comment]
`Other-ChapterNumber: '61.2.5'`
Dealing with floats normally, so it of course cant parse...
In Server V2 it will be fixed.
