### ISSUE TITLE
Monitored manga list getting emptied.

### ISSUE THREAD

**Issue by JohnnyBigoud** [C9Glax/tranga#48]
Hello,

It's not the first time my list of monitored manga is getting "removed" in the web UI. 
The tasks.json file is not empty.

I am using the docker containers.

tasks.json file below (hard to see in nano since there is new line character in the json).
![image](https://github.com/C9Glax/tranga/assets/20937336/2717e580-f58b-4737-bbf6-933f7af344b2)

UI - even after reload of the containers.
![image](https://github.com/C9Glax/tranga/assets/20937336/e8b2d5d5-c935-4a0e-83bc-c645427c40fc)

**Comment by C9Glax** [comment]
My quick guess:
Your browser clears cookies.
Check on the website top right corner settings: `API-URI`
If it still matches the tranga-api container IP+Port, please attach a screenshot of the "Network"-Tab in the developer-console (`F12`)

You can check if tranga-api is running by running `docker logs -f tranga-api`, it should still work in the background.

**Comment by JohnnyBigoud** [comment]
IP / port are matching the API ones.

It seems the issue is coming from the tranga-api container.
From what I understand one of the manga I added is triggering an error on startup.


`
-----------------------------------------------------------------
 |¯¯¯¯¯¯|°|¯¯¯¯¯¯\     /¯¯¯¯¯¯| |¯¯¯\|¯¯¯|  /¯¯¯¯¯¯\'   /¯¯¯¯¯¯| 
 |      | |   x  <|'  /   !   | |       '| |   (/¯¯¯\° /   !   | 
  ¯|__|¯  |__|\\__\\ /___/¯|_'| |___|\\__|  \\_____/' /___/¯|_'| 
-----------------------------------------------------------------
[09/07/2023 13:58:09.739]   TaskManager | Importing Data
[09/07/2023 13:58:09.739]   TaskManager | Importing tasks from /usr/share/Tranga-API/tasks.json
[09/07/2023 13:58:09.775]      Mangasee | Starting browser.
Unhandled exception. Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[424].chapter.parentPublication.tags[3]', line 1, position 859991.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Tranga.TrangaTasks.TrangaTask.TrangaTaskJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /src/Tranga/TrangaTasks/TrangaTask.cs:line 134
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tranga.TaskManager.ImportData() in /src/Tranga/TaskManager.cs:line 342
   at Tranga.TaskManager..ctor(TrangaSettings settings, Logger logger) in /src/Tranga/TaskManager.cs:line 39
   at Tranga.Tranga.Main(String[] args) in /src/Tranga/Tranga.cs:line 60
`

**Comment by C9Glax** [comment]
Huh yeah that seems to be the case.
If you have the ability to modify the tasks.json file, take a look at the 424th task-item (how many manga are you loading jesus).
A good online editor to look at specific item is:
https://jsonformatter.org/json-editor
Upload the file and switch to "tree-view".

If cou could then send a copy of that item here, that would be great to see what the heck that edge-case is.

**Comment by JohnnyBigoud** [comment]
Ok. I will look into it.
I am having only 10 mangas but starting from scratch so the 400+ entries are not mangas but chapters of one manga itself.

**Comment by JohnnyBigoud** [comment]
I am getting this in the file upload on your parser.

![image](https://github.com/C9Glax/tranga/assets/20937336/9fb09a2b-927d-41ef-815e-fde77707ac32)

Here is the tasks.json file
[tasks.zip](https://github.com/C9Glax/tranga/files/12563346/tasks.zip)

**Comment by C9Glax** [comment]
Well the file you sent me just ends after `Fanta`. So I guess I hit the column limit on json?
OR something interrupted the write... For now here is a "fixed" file that should get you up and running.
[tasks.zip](https://github.com/C9Glax/tranga/files/12566044/tasks.zip)
I guess this is something for #41 : Don't use a single file for all jobs?

**Comment by C9Glax** [comment]
@JohnnyBigoud did it work out?
I made the change to cuttingedge-branch, so this shouldn't happen again.

**Comment by C9Glax** [comment]
Closing as complete with #57

**Comment by JohnnyBigoud** [comment]
Sorry wasn’t to test lately. I’ve pulled new version. I will let you know if this occurs again.

**Comment by C9Glax** [comment]
No worries, I just closed because I finished the rewrite, and now the file that was making issues won't be created in that way anymore.
Check the README to update, but be aware that none of the present configs can be easily converted, meaning a lot of manual labor...
