### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#6]

**Comment by C9Glax** [comment]
no official .net core support for arm64

**Comment by schklom** [comment]
It looks like a trick allows to use `dotnet restore` for ARM: https://github.com/NuGet/Home/issues/12227#issuecomment-1592935099

I don't know much about this, but maybe worth a try?

**Comment by C9Glax** [comment]
Will take a look after my vacation, won't start debugging stuff while sitting in this lawnchair.

**Comment by bubez81** [comment]
very interested!

**Comment by BearTS** [comment]
+1 
is this still in the roadmap?

**Comment by C9Glax** [comment]
Yes, yes it should. I have no means to test if the built container actzually runs on ARM, but it at least builds

**Comment by bubez81** [comment]
Ok, but I'm receiving this error. am I doing something wrong?

Failed to pull images of the stack: tranga-website Pulling tranga-api Pulling no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by C9Glax** [comment]
Ah forgot the frontend . -. When at PC ii'll fix

**Comment by bubez81** [comment]
ok tnx! cuttingedge or latest?

**Comment by C9Glax** [comment]
Both should now also have built for arm 👍🏼

**Comment by bubez81** [comment]
mm are you sure?
Maybe I am doing something wrong:

services:
  tranga-api:
    platform: linux/arm64
#    image: glax/tranga-api:latest
    image: glax/tranga-api:cuttingedge
    container_name: tranga-api
    volumes:
      - /Volumes/Parcheggio/Lettura/Manga:/Manga
      - /opt/tranga:/usr/share/tranga-api
    environment:
      - TZ=Europe/Rome
      - USER_ID=502
      - GROUP_ID=20
    ports:
      - "6531:6531"
    restart: unless-stopped
  tranga-website:
    platform: linux/arm64
#    image: glax/tranga-website:latest
    image: glax/tranga-website:cuttingedge
    container_name: tranga-website
    ports:
      - "9555:80"
    depends_on: 
      - tranga-api
    restart: unless-stopped

**Comment by C9Glax** [comment]
No you werent, for some reason tranga-api:cuttingedge didn't build arm64... I am a bit confused, but checking the tags now it should have a arm64 image

**Comment by C9Glax** [comment]
This is a website error yeah, but people have also [reported that it is working](https://github.com/C9Glax/tranga/issues/247#issue-2517132013)... Gonna have to check myself first.

**Comment by bubez81** [comment]
Seems that the problem is only on cuttingedge

**Comment by bubez81** [comment]
not sure if this is related to this but this morning I notice this crash on Tranga-api:

'''
on Billy Bat YmlsbHliYXQyMDA4
[09/12/2024 08:26:51.228]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-bXlibGFzdGVkcmVpbmNhcm5hdGVkbGlmZTIwMjI= Manga: Publication My Blasted Reincarnated Life bXlibGFzdGVkcmVpbmNhcm5hdGVkbGlmZTIwMjI=
[09/12/2024 08:26:51.228]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-b25lcHVuY2htYW4yMDEy Manga: Publication One Punch-Man b25lcHVuY2htYW4yMDEy
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Manga/Solo Max-Level Newbie/series.json'.
File name: '/Manga/Solo Max-Level Newbie/series.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirError)
   at System.IO.FileStatus.SetUnixFileMode(SafeFileHandle handle, String path, UnixFileMode mode)
   at System.IO.File.SetUnixFileMode(String path, UnixFileMode mode)
   at Tranga.Manga.SaveSeriesInfoJson(Boolean overwrite) in /src/Tranga/Manga.cs:line 159
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 276
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 73
'''

and if I delete this manga, the error come with another manga
