### ISSUE TITLE
Mangasee 404 error crashes API container

### ISSUE THREAD

**Issue by Spencer-0003** [C9Glax/tranga#67]
### What is broken?

Attempting to download Chainsaw Man from Mangasee results in the API container crashing a few seconds after booting.

### Log-output

```C#
[10/15/2023 02:49:04.857]        Tranga | 

 _______                                   

|_     _|.----..---.-..-----..-----..---.-.

  |   |  |   _||  _  ||     ||  _  ||  _  |

  |___|  |__|  |___._||__|__||___  ||___._|

                             |_____|       

[10/15/2023 02:49:04.860]        Tranga | TrangaSettings:
	DownloadLocation: /Manga
	workingDirectory: /usr/share/tranga-api
	jobsFolderPath: /usr/share/tranga-api/jobs
	settingsFilePath: /usr/share/tranga-api/settings.json
		notificationConnectors: /usr/share/tranga-api/notificationConnectors.json
		libraryConnectors: /usr/share/tranga-api/libraryConnectors.json

[10/15/2023 02:49:04.869] ChromiumDownl | Starting Browser.
[10/15/2023 02:49:05.33 ]       JobBoss | Next job in -1.06:05:23.3593756 Tranga.Jobs.DownloadNewChapters-bGlhcmdhbWUyMDE5
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-aGlnaHNjaG9vbGR4ZDIwMTk= Manga: Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-dG9tb2RhY2hpZ2FtZTIwMTk= Manga: Publication Tomodachi Game dG9tb2RhY2hpZ2FtZTIwMTk=
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-c2FjaGlpcm9ub29uZXJvb20yMDE5 Manga: Publication Sachi-Iro No One Room c2FjaGlpcm9ub29uZXJvb20yMDE5
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-c2FpaGF0ZW5pbWFkb3UyMDIz Manga: Publication Saihate Ni Madou c2FpaGF0ZW5pbWFkb3UyMDIz
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-c2VyYXBob2Z0aGVlbmQyMDE5 Manga: Publication Seraph Of The End c2VyYXBob2Z0aGVlbmQyMDE5
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-ZWxmZW5saWVkMjAxOQ== Manga: Publication Elfen Lied ZWxmZW5saWVkMjAxOQ==
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-Ym9rdWRha2VnYWluYWltYWNoaTIwMTk= Manga: Publication Boku Dake Ga Inai Machi Ym9rdWRha2VnYWluYWltYWNoaTIwMTk=
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-a2FpZnVrdWp1dHN1c2hpbm95YXJpbmFvc2hpMjAxOQ== Manga: Publication Kaifuku Jutsushi No Yarinaoshi a2FpZnVrdWp1dHN1c2hpbm95YXJpbmFvc2hpMjAxOQ==
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-YmF0dGxlaW5zZWNvbmRzYWZ0ZXJtZWV0aW5nMjAyMg== Manga: Publication Battle In 5 Seconds After Meeting YmF0dGxlaW5zZWNvbmRzYWZ0ZXJtZWV0aW5nMjAyMg==
[10/15/2023 02:49:05.35 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-ZGVhZG1hbndvbmRlcmxhbmQyMDE5 Manga: Publication Deadman Wonderland ZGVhZG1hbndvbmRlcmxhbmQyMDE5
[10/15/2023 02:49:05.36 ]     Manganato | Getting new Chapters for Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.36 ]     Manganato | Getting chapters Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.38 ]        Server | Listening on http://*:6531/
[10/15/2023 02:49:05.219]     Manganato | Got 35 chapters. Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.221]     Manganato | Checking for duplicates Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.272]     Manganato | 0 new chapters. Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.273]     Manganato | Copy cover Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.273]     Manganato | Cover exists Publication High-School Dxd aGlnaHNjaG9vbGR4ZDIwMTk=
[10/15/2023 02:49:05.374]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-bGlhcmdhbWUyMDE5 Manga: Publication Liar Game bGlhcmdhbWUyMDE5
[10/15/2023 02:49:05.374]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-Y2hhaW5zYXdtYW4yMDE4 Manga: Publication Chainsaw Man Y2hhaW5zYXdtYW4yMDE4
[10/15/2023 02:49:05.374]       JobBoss | Next job in -1.06:05:23.7005980 Tranga.Jobs.DownloadNewChapters-bGlhcmdhbWUyMDE5
[10/15/2023 02:49:05.374]      Mangasee | Getting new Chapters for Publication Chainsaw Man Y2hhaW5zYXdtYW4yMDE4
[10/15/2023 02:49:05.375]      Mangasee | Getting chapters Publication Chainsaw Man Y2hhaW5zYXdtYW4yMDE4

Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetNonFileStreamAsync(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Tranga.MangaConnectors.Mangasee.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangasee.cs:line 119
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 59
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
   at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 73
```

**Comment by C9Glax** [comment]
Hey there,
thanks for reporting, I pushed an exception handling fix, that should allow jobs that 404 to cancel correctly without crashing.
I will leave this open, if you think the issue is fixed, feel free to close.

**Comment by Spencer-0003** [comment]
The issue is fixed, downloads are completing and my container isn't crashing. Thanks!
