### ISSUE TITLE
[It broke]: The input string 'Bonus' was not in a correct format.

### ISSUE THREAD

**Issue by ProfesseurIssou** [C9Glax/tranga#70]
### What is broken?

I added a manga on mangakatana, but after that, the webUI still stuck on Check your Settings > API-URI
I tried to re-deploy but it doesn't work

### Log-output

```C#
Unhandled exception. System.FormatException: The input string 'Bonus' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Convert.ToSingle(String value, IFormatProvider provider)
   at Tranga.MangaConnectors.MangaKatana.<>c.<GetChapters>b__5_0(Chapter chapter) in /src/Tranga/MangaConnectors/MangaKatana.cs:line 157
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.SortedMap(Buffer`1 buffer)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tranga.MangaConnectors.MangaKatana.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaKatana.cs:line 157
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 59
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
   at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Yea that's a parsing error, Regex related.
Can you tell me which Manga you got this on? I see it's MangaKatana, but I would need the name, or even better a URL.

**Comment by MinouCrew** [comment]
Same for me, on the latest tag on docker
Other manga work but this one https://mangakatana.com/manga/isekai-elf-no-dorei-chan.20015 has a chapter named "Chapter Bonus" instead of "Chapter {No}: {name}"

**Comment by C9Glax** [comment]
I pushed a possible fix to `cuttingedge` if you could test it and report back or just close if it works, that would be great

**Comment by MinouCrew** [comment]
It's working for me, thank you

**Comment by ProfesseurIssou** [comment]
Me too, thank you

**Comment by C9Glax** [comment]
Cheers, closing
