### ISSUE TITLE
[It broke]: Mangasee | Failed to load XML

### ISSUE THREAD

**Issue by MinouCrew** [C9Glax/tranga#76]
### What is broken?

Hello,
I use the cuttingedge version and when the API start, he got stuck at the scan

### Log-output

```C#
[10/31/2023 10:13:10.187]      Mangasee | Getting new Chapters for Publication Creature Girls: A Hands-On Field Journal in Another World Y3JlYXR1cmVnaXJsc2FoYW5kc29uZmllbGRqb3VybmFsaW5hbm90aGVyd29ybGQyMDE3
[10/31/2023 10:13:10.187]      Mangasee | Getting chapters Publication Creature Girls: A Hands-On Field Journal in Another World Y3JlYXR1cmVnaXJsc2FoYW5kc29uZmllbGRqb3VybmFsaW5hbm90aGVyd29ybGQyMDE3
[10/31/2023 10:13:10.296]      Mangasee | Failed to load XML

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetNonFileStreamAsync(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Tranga.MangaConnectors.Mangasee.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangasee.cs:line 126
[10/31/2023 10:13:10.296]      Mangasee | Checking for duplicates Publication Creature Girls: A Hands-On Field Journal in Another World Y3JlYXR1cmVnaXJsc2FoYW5kc29uZmllbGRqb3VybmFsaW5hbm90aGVyd29ybGQyMDE3
[10/31/2023 10:13:10.296]      Mangasee | 0 new chapters. Publication Creature Girls: A Hands-On Field Journal in Another World Y3JlYXR1cmVnaXJsc2FoYW5kc29uZmllbGRqb3VybmFsaW5hbm90aGVyd29ybGQyMDE3
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 65
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
   at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment]
Okay I can't reproduce right now, however I have seen this happen before, where the RSS-Feed goes down for whatever reason.

**Comment by MinouCrew** [comment]
So i just need to wait until the RSS-Feed come back ?

**Comment by C9Glax** [comment]
Which it has for me, you still get the 404?

**Comment by MinouCrew** [comment]
I just retry and yes i still get the 404

**Comment by C9Glax** [comment]
Okay I added more information to the log.
What I can already see: The publication-name changed, and I don't know if that also affects the rss-feed

**Comment by C9Glax** [comment]
seems like your container isnt updated yet. run `docker compose pull && docker compose up -d`

**Comment by MinouCrew** [comment]
[10/31/2023 16:10:28.69 ]      Mangasee | Getting new Chapters for Publication Ayakashi Triangle YXlha2FzaGl0cmlhbmdsZTIwMjA=
[10/31/2023 16:10:28.69 ]      Mangasee | Getting chapters Publication Ayakashi Triangle YXlha2FzaGl0cmlhbmdsZTIwMjA=
[10/31/2023 16:10:28.184]      Mangasee | Failed to load https://mangasee123.com/rss/b49db7e7-0637-462c-9d09-372f5d09de4a.xml 

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetNonFileStreamAsync(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Tranga.MangaConnectors.Mangasee.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangasee.cs:line 180
[10/31/2023 16:10:28.184]      Mangasee | Checking for duplicates Publication Ayakashi Triangle YXlha2FzaGl0cmlhbmdsZTIwMjA=
[10/31/2023 16:10:28.184]      Mangasee | 0 new chapters. Publication Ayakashi Triangle YXlha2FzaGl0cmlhbmdsZTIwMjA=
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 65
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
   at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74

**Comment by C9Glax** [comment]
yeah that site doesn't exist...
I will take a look later how that ended up there...

**Comment by MinouCrew** [comment]
Hello, i repull the image, and delete the manga to unlock Tranga api, but two others manga has 404, this is the last one

[11/03/2023 19:32:45.821]      Mangasee | Getting new Chapters for Publication Chanto Suenai Kyuuketsuki-chan Y2hhbnRvc3VlbmFpa3l1dWtldHN1a2ljaGFuMjAyMQ==
[11/03/2023 19:32:45.821]      Mangasee | Getting chapters Publication Chanto Suenai Kyuuketsuki-chan Y2hhbnRvc3VlbmFpa3l1dWtldHN1a2ljaGFuMjAyMQ==
[11/03/2023 19:32:45.960]      Mangasee | Failed to load https://mangasee123.com/rss/334b3730-21a7-4293-af2f-4875abd08ed1.xml 

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetNonFileStreamAsync(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Tranga.MangaConnectors.Mangasee.GetChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/Mangasee.cs:line 194
[11/03/2023 19:32:45.960]      Mangasee | Checking for duplicates Publication Chanto Suenai Kyuuketsuki-chan Y2hhbnRvc3VlbmFpa3l1dWtldHN1a2ljaGFuMjAyMQ==
[11/03/2023 19:32:45.960]      Mangasee | 0 new chapters. Publication Chanto Suenai Kyuuketsuki-chan Y2hhbnRvc3VlbmFpa3l1dWtldHN1a2ljaGFuMjAyMQ==
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 67
   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74

**Comment by C9Glax** [comment]
Okay my issue with this is, that URL: `https://mangasee123.com/rss/334b3730-21a7-4293-af2f-4875abd08ed1.xml `
This URL is generated from the publication ID we parse from the URL, but Mangasee (at least for me) uses URLs in a completely different format: `https://mangasee123.com/manga/Theres-No-Freaking-Way-Ill-Be-Your-Lover-Unless`
So if you tell me how you added the Manga to Tranga, I could think of a way...

**Comment by MinouCrew** [comment]
I use the UI, select Mangasee, put the name and add the job

**Comment by MinouCrew** [comment]
i try to remove and re-add the manga and it seem to work, but now i am stuck because the website can't call the API "Check your Settings > API-URI", i think it's because of the buggy manga cause a crash of the API, and i can't remove the manga

**Comment by db-2001** [comment]
I know this is bit of a late reply but my approach is monitor the logs of the tranga container in portainer and then as soon as the server starts listening for connections, load the front end and delete the manga before it gets to the job for it. It's a bit jank but it works for the time being until there is better error handling.

**Comment by C9Glax** [comment]
If you want to delete the job there is also the full jobid in the logs, so you can just delete the associate .json file in the jobs folder

**Comment by MinouCrew** [comment]
nice, i just finished to remove all buggy manga, thank you

**Comment by C9Glax** [comment]
@MinouCrew no more issues? Then please close 🙇🏼‍♀️
