### ISSUE TITLE
[It broke]: Chiisai Gyaru on Mangadex crashes Tranga repeatedly 

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#87]
### What is broken?

Once tranga encounters the manga "Chiisai Gyaru" on Mangadex it generates an error and crashes. This didn't happen earlier so I'm not sure what causes it.

### Log-output

```C#
[11/30/2023 03:53:15.456]      MangaDex | Getting new Chapters for Publication Chiisai Gyaru Y2hpaXNhaWd5YXJ1MjAyMw==

[11/30/2023 03:53:15.456]      MangaDex | Getting chapters Publication Chiisai Gyaru Y2hpaXNhaWd5YXJ1MjAyMw==

[11/30/2023 03:53:15.456] HttpDownloadC | Waiting 0.0268446 seconds

[11/30/2023 03:53:15.788]      MangaDex | Got 0 chapters. Publication Chiisai Gyaru Y2hpaXNhaWd5YXJ1MjAyMw==

[11/30/2023 03:53:15.813]      MangaDex | Checking for duplicates Publication Chiisai Gyaru Y2hpaXNhaWd5YXJ1MjAyMw==

[11/30/2023 03:53:15.814]      MangaDex | 0 new chapters. Publication Chiisai Gyaru Y2hpaXNhaWd5YXJ1MjAyMw==

Unhandled exception. System.InvalidOperationException: Sequence contains no elements

   at System.Linq.ThrowHelper.ThrowNoElementsException()

   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)

   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)

   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 67

   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37

   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 94

   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 240

   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74

[11/30/2023 03:53:42.487]        Tranga |
```

**Comment by C9Glax** [comment]
Yea but I still think this was an issue with Manga that had no chapters yet, so I pushed a fix for that too
