### ISSUE TITLE
[It broke]: The input string '' was not in a correct format

### ISSUE THREAD

**Issue by Gravewish** [C9Glax/tranga#93]
### What is broken?

I recently set up Tranga and added "Grand Blue Dreaming" and "Sono Bisque Doll". Everything was working well, when all of a sudden Tranga bricked itself, immediately failing during startup.

This essentially makes using Tranga impossible, as it crashes at startup.

### Log-output

```C#
Dec 21 13:53:14 media podman[2774588]: 2023-12-21 13:52:42.203157481 +0000 GMT m=+0.030754160 image pull  docker.io/glax/tranga-api:cuttingedge
Dec 21 13:53:14 media podman[2774588]: 
Dec 21 13:53:14 media podman[2774588]: 2023-12-21 13:53:14.745226088 +0000 GMT m=+32.572822320 container create 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df (image=docker.io/glax/tranga-api:cuttingedge, name=tranga-api, pod_id=2ab7b17f88e738dd46f9c92d265a9a7567676713b6d35f669dfcb2811c5dd72b, io.containers.autoupdate=registry, PODMAN_SYSTEMD_UNIT=tranga-pod:tranga-api.service)
Dec 21 13:53:14 media podman[2774588]: 2023-12-21 13:53:14.851117839 +0000 GMT m=+32.678713950 container init 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df (image=docker.io/glax/tranga-api:cuttingedge, name=tranga-api, pod_id=2ab7b17f88e738dd46f9c92d265a9a7567676713b6d35f669dfcb2811c5dd72b, io.containers.autoupdate=registry, PODMAN_SYSTEMD_UNIT=tranga-pod:tranga-api.service)
Dec 21 13:53:14 media podman[2774588]: 2023-12-21 13:53:14.859583122 +0000 GMT m=+32.687179591 container start 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df (image=docker.io/glax/tranga-api:cuttingedge, name=tranga-api, pod_id=2ab7b17f88e738dd46f9c92d265a9a7567676713b6d35f669dfcb2811c5dd72b, PODMAN_SYSTEMD_UNIT=tranga-pod:tranga-api.service, io.containers.autoupdate=registry)
Dec 21 13:53:14 media tranga-pod:tranga-api[2774588]: 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df
Dec 21 13:53:15 media tranga-api[2775704]: [12/21/2023 13:53:15.133]        Tranga | 
Dec 21 13:53:15 media tranga-api[2775704]: 
Dec 21 13:53:15 media tranga-api[2775704]:  _______                                   
Dec 21 13:53:15 media tranga-api[2775704]: |_     _|.----..---.-..-----..-----..---.-.
Dec 21 13:53:15 media tranga-api[2775704]:   |   |  |   _||  _  ||     ||  _  ||  _  |
Dec 21 13:53:15 media tranga-api[2775704]:   |___|  |__|  |___._||__|__||___  ||___._|
Dec 21 13:53:15 media tranga-api[2775704]:                              |_____|       
Dec 21 13:53:15 media tranga-api[2775704]: 
Dec 21 13:53:15 media tranga-api[2775704]: 
Dec 21 13:53:15 media tranga-api[2775704]: [12/21/2023 13:53:15.147]        Tranga | TrangaSettings:
Dec 21 13:53:15 media tranga-api[2775704]:         DownloadLocation: /Manga
Dec 21 13:53:15 media tranga-api[2775704]:         workingDirectory: /usr/share/tranga-api
Dec 21 13:53:15 media tranga-api[2775704]:         jobsFolderPath: /usr/share/tranga-api/jobs
Dec 21 13:53:15 media tranga-api[2775704]:         settingsFilePath: /usr/share/tranga-api/settings.json
Dec 21 13:53:15 media tranga-api[2775704]:                 notificationConnectors: /usr/share/tranga-api/notificationConnectors.json
Dec 21 13:53:15 media tranga-api[2775704]:                 libraryConnectors: /usr/share/tranga-api/libraryConnectors.json
Dec 21 13:53:15 media tranga-api[2775704]: 
Dec 21 13:53:15 media tranga-api[2775704]: [12/21/2023 13:53:15.160] ChromiumDownl | Downloading headless browser
Dec 21 13:53:15 media tranga-api[2775704]: [12/21/2023 13:53:15.725] ChromiumDownl | Browser download progress: 0.00 %
Dec 21 13:53:16 media tranga-api[2775704]: [12/21/2023 13:53:16.725] ChromiumDownl | Browser download progress: 11.97 %
Dec 21 13:53:16 media tranga-api[2775704]: [12/21/2023 13:53:16.725] ChromiumDownl | Browser download progress: 11.98 %
Dec 21 13:53:17 media tranga-api[2775704]: [12/21/2023 13:53:17.731] ChromiumDownl | Browser download progress: 39.22 %
Dec 21 13:53:17 media tranga-api[2775704]: [12/21/2023 13:53:17.731] ChromiumDownl | Browser download progress: 39.23 %
Dec 21 13:53:18 media tranga-api[2775704]: [12/21/2023 13:53:18.736] ChromiumDownl | Browser download progress: 66.61 %
Dec 21 13:53:19 media tranga-api[2775704]: [12/21/2023 13:53:19.739] ChromiumDownl | Browser download progress: 95.21 %
Dec 21 13:53:19 media tranga-api[2775704]: [12/21/2023 13:53:19.739] ChromiumDownl | Browser download progress: 95.22 %
Dec 21 13:53:19 media tranga-api[2775704]: [12/21/2023 13:53:19.920] ChromiumDownl | Browser downloaded.
Dec 21 13:53:21 media tranga-api[2775704]: [12/21/2023 13:53:21.697] ChromiumDownl | Starting Browser.
Dec 21 13:53:21 media tranga-api[2775704]: [12/21/2023 13:53:21.896] ChromiumDownl | Starting Browser.
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.11 ]       JobBoss | Next job in -2.21:13:18.3574092 Tranga.Jobs.DownloadNewChapters-Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.15 ]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-Z3JhbmRibHVlMjAxOQ== Manga: Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.17 ]     Manganato | Getting new Chapters for Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.18 ]     Manganato | Getting chapters Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.21 ]        Server | Listening on http://*:6531/
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.383]     Manganato | Got 118 chapters. Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.386]     Manganato | Checking for duplicates Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: [12/21/2023 13:53:22.387]     Manganato | 0 new chapters. Publication Grand Blue Z3JhbmRibHVlMjAxOQ==
Dec 21 13:53:22 media tranga-api[2775704]: Unhandled exception. System.FormatException: The input string '' was not in a correct format.
Dec 21 13:53:22 media tranga-api[2775704]:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
Dec 21 13:53:22 media tranga-api[2775704]:    at System.Convert.ToSingle(String value, IFormatProvider provider)
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.MangaConnectors.MangaConnector.<>c.<GetNewChapters>b__13_1(Chapter chapter) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 68
Dec 21 13:53:22 media tranga-api[2775704]:    at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
Dec 21 13:53:22 media tranga-api[2775704]:    at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 67
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/DownloadNewChapters.cs:line 37
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
Dec 21 13:53:22 media tranga-api[2775704]:    at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
Dec 21 13:53:22 media podman[2775929]: 2023-12-21 13:53:22.460273844 +0000 GMT m=+0.026547310 container died 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df (image=docker.io/glax/tranga-api:cuttingedge, name=tranga-api, PODMAN_SYSTEMD_UNIT=tranga-pod:tranga-api.service, io.containers.autoupdate=registry)
Dec 21 13:53:25 media podman[2775929]: 2023-12-21 13:53:25.787774913 +0000 GMT m=+3.354048342 container remove 214294d5256158f3c07a4d165cce5d5e123c0b4ed78e818381e02fe9c7f7f3df (image=docker.io/glax/tranga-api:cuttingedge, name=tranga-api, pod_id=2ab7b17f88e738dd46f9c92d265a9a7567676713b6d35f669dfcb2811c5dd72b, PODMAN_SYSTEMD_UNIT=tranga-pod:tranga-api.service, io.containers.autoupdate=registry)
```

### Additional stuff

I'm running the latest `cuttingedge` version under Podman instead of Docker, which is why the log format is slightly different.

**Comment by Charles-Em** [comment]
Same problem on latest version, was also on a MangaNato answer for me

**Comment by db-2001** [comment]
I'm also having this same issue on Manganato

**Comment by stzehn** [comment]
Same here broke on Manganato "Unhandled exception. System.FormatException: The input string '' was not in a correct format." that then puts it in an endless restart loop. Any way to stop the loop and kick the Manganato job out ? Mangadex was still working ;-)

**Comment by C9Glax** [comment]
Okay I think I found the issue:
Manganato changed their domain for chapters to `.to` breaking the regex that parses chapter-numbers.
Fix is pushed.
