### ISSUE TITLE
[It broke]: Mangasee destroys tranga

### ISSUE THREAD

**Issue by m8dotpie** [C9Glax/tranga#94]
### What is broken?

Trying to download manga from mangasee, jojolands in particular. Tranga crashes. Can not empty the jobs list, as a result tranga is in continuous crash.

### Log-output

```C#
tranga.api  | [12/31/2023 10:47:25.773] ChromiumDownl | Starting Browser.
tranga.api  | [12/31/2023 10:47:27.82 ] ChromiumDownl | Starting Browser.
tranga.api  | [12/31/2023 10:47:27.657]       JobBoss | Next job in -00:03:13.6458335 Tranga.Jobs.DownloadNewChapters-am9qb3NiaXphcnJlYWR2ZW50dXJlcGFydHRoZWpvam9sYW5kczIwMjM=
tranga.api  | [12/31/2023 10:47:27.671]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-am9qb3NiaXphcnJlYWR2ZW50dXJlcGFydHRoZWpvam9sYW5kczIwMjM= Manga: Publication Jojo's Bizarre Adventure Part 9 - The Jojolands am9qb3NiaXphcnJlYWR2ZW50dXJlcGFydHRoZWpvam9sYW5kczIwMjM=
tranga.api  | [12/31/2023 10:47:27.701]        Server | Listening on http://*:6531/
tranga.api  | [12/31/2023 10:47:31.856] ChromiumDownl | Page loaded.
tranga.api  | Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
tranga.api  |    at Tranga.MangaConnectors.Mangasee.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 137
tranga.api  |    at Tranga.MangaConnectors.Mangasee.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/Mangasee.cs:line 126
tranga.api  |    at Tranga.MangaConnectors.Mangasee.GetMangaFromId(String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 116
tranga.api  |    at Tranga.Jobs.UpdateMetadata.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/UpdateMetadata.cs:line 27
tranga.api  |    at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
tranga.api  |    at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
tranga.api  |    at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
tranga.api exited with code 0
```

**Comment by C9Glax** [comment]
Okay I think the problem is that HTMLAgilityPack has not been able to correctly parse the website for whatever reason.
If you haven't already tried: Delete the Job `Tranga.Jobs.DownloadNewChapters-am9qb3NiaXphcnJlYWR2ZW50dXJlcGFydHRoZWpvam9sYW5kczIwMjM=` .json file and restart Tranga.
If the problem persists please update this issue.

**Comment by m8dotpie** [comment]
I have rebuilt the container to quickly get it running. I will check later if the issue with mangasee persists

**Comment by m8dotpie** [comment]
Somehow it is fine now, could not replicate
