### ISSUE TITLE
[It broke]: Manga chapter download failing

### ISSUE THREAD

**Issue by Nas-77** [C9Glax/tranga#99]
### What is broken?

Found that the download jobs were failing due to the HttpRequest timing out.

### Log-output

```C#
[01/12/2024 15:21:28.859]       JobBoss | Next job in -19734.15:21:28.8594925 Tranga.Jobs.DownloadChapter-aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx-90
[01/12/2024 15:21:28.960]     Manganato | Copy cover Publication I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx
[01/12/2024 15:21:28.961]     Manganato | Cover exists Publication I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx
[01/12/2024 15:21:28.961]     Manganato | Retrieving chapter-info Chapter I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx 94  Publication I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx
[01/12/2024 15:21:28.961] HttpDownloadC | Waiting 0.8267717 seconds
[01/12/2024 15:21:30.307]     Manganato | Downloading Images for /Manga/I Become A Fool When It Comes To My Daughter/I Become A Fool When It Comes To My Daughter - Vol.0 Ch.94 .cbz
[01/12/2024 15:21:30.307]     Manganato | Downloading image 001/016
[01/12/2024 15:21:30.307] HttpDownloadC | Waiting 0.9991803 seconds
[01/12/2024 15:21:31.527]     Manganato | /Manga/I Become A Fool When It Comes To My Daughter/I Become A Fool When It Comes To My Daughter - Vol.0 Ch.94 .cbz 002/016 OK
[01/12/2024 15:21:31.527]     Manganato | Downloading image 002/016
[01/12/2024 15:21:31.527] HttpDownloadC | Waiting 0.9962421 seconds
[01/12/2024 15:22:21.22 ]     Manganato | /Manga/I Become A Fool When It Comes To My Daughter/I Become A Fool When It Comes To My Daughter - Vol.0 Ch.94 .cbz 003/016 OK
[01/12/2024 15:22:21.22 ]     Manganato | Downloading image 003/016
[01/12/2024 15:22:21.22 ] HttpDownloadC | Waiting 0.9983511 seconds
[01/12/2024 15:23:22.25 ] HttpDownloadC | Request timed out.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Software caused connection abort.
 ---> System.Net.Sockets.SocketException (103): Software caused connection abort
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.Read(Span`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStream(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBuffer(Int64 maxBufferSize, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBuffer(Int64 maxBufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Tranga.MangaConnectors.HttpDownloadClient.MakeRequestInternal(String url, String referrer, String clickButton) in /src/Tranga/MangaConnectors/HttpDownloadClient.cs:line 82
[01/12/2024 15:23:22.25 ]     Manganato | /Manga/I Become A Fool When It Comes To My Daughter/I Become A Fool When It Comes To My Daughter - Vol.0 Ch.94 .cbz 004/016 RequestTimeout
[01/12/2024 15:23:22.116]       JobBoss | Removing Tranga.Jobs.DownloadChapter-aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx-94 Chapter: Chapter I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx 94 
[01/12/2024 15:23:22.116] DownloadChapt | Cancelling Tranga.Jobs.DownloadChapter-aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx-94 Chapter: Chapter I Become A Fool When It Comes To My Daughter aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx 94 
[01/12/2024 15:23:22.117]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadChapter-aWJlY29tZWFmb29sd2hlbml0Y29tZXN0b215ZGF1Z2h0ZXIyMDIx-94.json
```

**Comment by C9Glax** [comment]
Pretty normal.
Nothing Tranga can really do if the request times out, e.g. the connection to the server is interrupted, or the server can not serve the page.
Tranga will try again on the next cycle to download that chapter.
